[[startup]]
= Application Startup (`startup`)

The `startup` endpoint provides information about the application's startup sequence.



[[startup.retrieving]]
== Retrieving the Application Startup Steps

The application startup steps can either be retrieved as a snapshot (`GET`) or drained from the buffer (`POST`).



[[startup.retrieving.snapshot]]
=== Retrieving a snapshot of the Application Startup Steps

To retrieve the steps recorded so far during the application startup phase, make a `GET` request to `/actuator/startup`, as shown in the following curl-based example:

include::partial$rest/actuator/startup-snapshot/curl-request.adoc[]

The resulting response is similar to the following:

include::partial$rest/actuator/startup-snapshot/http-response.adoc[]



[[startup.retrieving.drain]]
=== Draining the Application Startup Steps

To drain and return the steps recorded so far during the application startup phase, make a `POST` request to `/actuator/startup`, as shown in the following curl-based example:

include::partial$rest/actuator/startup/curl-request.adoc[]

The resulting response is similar to the following:

include::partial$rest/actuator/startup/http-response.adoc[]



[[startup.retrieving.response-structure]]
=== Response Structure

The response contains details of the application startup steps.
The following table describes the structure of the response:

[cols="2,1,3"]
include::partial$rest/actuator/startup/response-fields.adoc[]
