= 构建系统
:encoding: utf-8
:numbered:

[[using.build-systems]]
== 构建系统
强烈建议你选择支持 xref:using/build-systems.adoc#using.build-systems.dependency-management[依赖管理] 并能够使用发布到 Maven 中央仓库的工件的构建系统。
我们建议你选择 Maven 或 Gradle。
虽然可以让 Spring Boot 与其他构建系统（例如 Ant）一起工作，但它们并未得到特别好的支持。

[[using.build-systems.dependency-management]]
== 依赖管理
每个 Spring Boot 版本都提供了一个经过筛选的依赖列表。
实际上，你无需在构建配置中为这些依赖提供版本号，因为 Spring Boot 会为你管理这些依赖。
当你升级 Spring Boot 时，这些依赖也会以一致的方式升级。

NOTE: 如果需要，你仍然可以指定版本并覆盖 Spring Boot 的推荐版本。

这个经过筛选的列表包含所有可以与 Spring Boot 一起使用的 Spring 模块以及精选的第三方库。
该列表以标准的物料清单（`spring-boot-dependencies`）形式提供，可以与 xref:using/build-systems.adoc#using.build-systems.maven[Maven] 和 xref:using/build-systems.adoc#using.build-systems.gradle[Gradle] 一起使用。

WARNING: 每个 Spring Boot 版本都与 Spring Framework 的基础版本相关联。
我们**强烈**建议你不要指定其版本。

[[using.build-systems.maven]]
== Maven
要了解如何将 Spring Boot 与 Maven 一起使用，请参阅 Spring Boot 的 Maven 插件文档：

* xref:maven-plugin:index.adoc[参考文档]
* xref:maven-plugin:api/java/index.html[API 文档]

[[using.build-systems.gradle]]
== Gradle
要了解如何将 Spring Boot 与 Gradle 一起使用，请参阅 Spring Boot 的 Gradle 插件文档：

* xref:gradle-plugin:index.adoc[参考文档]
* xref:gradle-plugin:api/java/index.html[API 文档]

[[using.build-systems.ant]]
== Ant
可以使用 Apache Ant+Ivy 构建 Spring Boot 项目。
`spring-boot-antlib` "`AntLib`" 模块也可用于帮助 Ant 创建可执行的 jar 文件。

要声明依赖项，典型的 `ivy.xml` 文件如下所示：

[source,xml]
----
<ivy-module version="2.0">
	<info organisation="org.springframework.boot" module="spring-boot-sample-ant" />
	<configurations>
		<conf name="compile" description="编译此模块所需的一切" />
		<conf name="runtime" extends="compile" description="运行此模块所需的一切" />
	</configurations>
	<dependencies>
		<dependency org="org.springframework.boot" name="spring-boot-starter"
			rev="${spring-boot.version}" conf="compile" />
	</dependencies>
</ivy-module>
----

典型的 `build.xml` 文件如下所示：

[source,xml,subs="verbatim,attributes"]
----
<project
	xmlns:ivy="antlib:org.apache.ivy.ant"
	xmlns:spring-boot="antlib:org.springframework.boot.ant"
	name="myapp" default="build">

	<property name="spring-boot.version" value="{version-spring-boot}" />

	<target name="resolve" description="--> retrieve dependencies with ivy">
		<ivy:retrieve pattern="lib/[conf]/[artifact]-[type]-[revision].[ext]" />
	</target>

	<target name="classpaths" depends="resolve">
		<path id="compile.classpath">
			<fileset dir="lib/compile" includes="*.jar" />
		</path>
	</target>

	<target name="init" depends="classpaths">
		<mkdir dir="build/classes" />
	</target>

	<target name="compile" depends="init" description="compile">
		<javac srcdir="src/main/java" destdir="build/classes" classpathref="compile.classpath" />
	</target>

	<target name="build" depends="compile">
		<spring-boot:exejar destfile="build/myapp.jar" classes="build/classes">
			<spring-boot:lib>
				<fileset dir="lib/runtime" />
			</spring-boot:lib>
		</spring-boot:exejar>
	</target>
</project>
----

TIP: 如果你不想使用 `spring-boot-antlib` 模块，请参阅 "`操作指南`" 中的 xref:how-to:build.adoc#howto.build.build-an-executable-archive-with-ant-without-using-spring-boot-antlib[] 部分。


[[using.build-systems.starters]]
== Starters
Starters 是一组方便的依赖描述符，你可以将其包含在你的应用程序中。
你可以一站式获取所有 Spring 和相关技术所需的依赖，而无需通过示例代码搜索并复制粘贴大量的依赖描述符。
例如，如果你想开始使用 Spring 和 JPA 进行数据库访问，请在你的项目中包含 `spring-boot-starter-data-jpa` 依赖。

Starters 包含了许多你需要的依赖，以便快速启动和运行项目，并提供了一组一致且受管理的传递依赖。

.命名规则
****
所有**官方** starters 都遵循类似的命名模式：`+spring-boot-starter-*+`，其中 `+*+` 是特定类型的应用程序。
这种命名结构旨在帮助你找到所需的 starter。
许多 IDE 中的 Maven 集成允许你按名称搜索依赖项。
例如，安装了适当的 Eclipse 或 Spring Tools 插件后，你可以在 POM 编辑器中按 `ctrl-space` 并输入 "`spring-boot-starter`" 以获取完整列表。

如 xref:features/developing-auto-configuration.adoc#features.developing-auto-configuration.custom-starter[] 部分所述，第三方 starters 不应以 `spring-boot` 开头，因为这是为官方 Spring Boot 工件保留的。
相反，第三方 starter 通常以项目名称开头。
例如，一个名为 `thirdpartyproject` 的第三方 starter 项目通常会被命名为 `thirdpartyproject-spring-boot-starter`。
****

Spring Boot 在 `org.springframework.boot` 组下提供了以下应用程序 starters：

.Spring Boot 应用程序 starters
include::starters/application-starters.adoc[]

除了应用程序 starters 外，以下 starters 可用于添加 xref:how-to:actuator.adoc[生产就绪] 功能：

.Spring Boot 生产 starters
include::starters/production-starters.adoc[]

最后，Spring Boot 还包括以下 starters，如果你想排除或替换特定的技术方面，可以使用它们：

.Spring Boot 技术 starters
include::starters/technical-starters.adoc[]

要了解如何替换技术方面，请参阅 xref:how-to:webserver.adoc#howto.webserver.use-another[替换 Web 服务器] 和 xref:how-to:logging.adoc#howto.logging.log4j[日志系统] 的操作指南文档。

TIP: 有关社区贡献的其他 starters 列表，请参阅 GitHub 上 `spring-boot-starters` 模块中的 {code-spring-boot-latest}/spring-boot-project/spring-boot-starters/README.adoc[README 文件]。

'''
[[using.build-systems]]
== Build Systems
It is strongly recommended that you choose a build system that supports xref:using/build-systems.adoc#using.build-systems.dependency-management[dependency management] and that can consume artifacts published to the Maven Central repository.
We would recommend that you choose Maven or Gradle.
It is possible to get Spring Boot to work with other build systems (Ant, for example), but they are not particularly well supported.

[[using.build-systems.dependency-management]]
== Dependency Management
Each release of Spring Boot provides a curated list of dependencies that it supports.
In practice, you do not need to provide a version for any of these dependencies in your build configuration, as Spring Boot manages that for you.
When you upgrade Spring Boot itself, these dependencies are upgraded as well in a consistent way.

NOTE: You can still specify a version and override Spring Boot's recommendations if you need to do so.

The curated list contains all the Spring modules that you can use with Spring Boot as well as a refined list of third party libraries.
The list is available as a standard Bills of Materials (`spring-boot-dependencies`) that can be used with both xref:using/build-systems.adoc#using.build-systems.maven[Maven] and xref:using/build-systems.adoc#using.build-systems.gradle[Gradle].

WARNING: Each release of Spring Boot is associated with a base version of the Spring Framework.
We **highly** recommend that you do not specify its version.

[[using.build-systems.maven]]
== Maven
To learn about using Spring Boot with Maven, see the documentation for Spring Boot's Maven plugin:

* xref:maven-plugin:index.adoc[Reference]
* xref:maven-plugin:api/java/index.html[API]

[[using.build-systems.gradle]]
== Gradle
To learn about using Spring Boot with Gradle, see the documentation for Spring Boot's Gradle plugin:

* xref:gradle-plugin:index.adoc[Reference]
* xref:gradle-plugin:api/java/index.html[API]

[[using.build-systems.ant]]
==  Ant
It is possible to build a Spring Boot project using Apache Ant+Ivy.
The `spring-boot-antlib` "`AntLib`" module is also available to help Ant create executable jars.

To declare dependencies, a typical `ivy.xml` file looks something like the following example:

[source,xml]
----
<ivy-module version="2.0">
	<info organisation="org.springframework.boot" module="spring-boot-sample-ant" />
	<configurations>
		<conf name="compile" description="everything needed to compile this module" />
		<conf name="runtime" extends="compile" description="everything needed to run this module" />
	</configurations>
	<dependencies>
		<dependency org="org.springframework.boot" name="spring-boot-starter"
			rev="${spring-boot.version}" conf="compile" />
	</dependencies>
</ivy-module>
----

A typical `build.xml` looks like the following example:

[source,xml,subs="verbatim,attributes"]
----
<project
	xmlns:ivy="antlib:org.apache.ivy.ant"
	xmlns:spring-boot="antlib:org.springframework.boot.ant"
	name="myapp" default="build">

	<property name="spring-boot.version" value="{version-spring-boot}" />

	<target name="resolve" description="--> retrieve dependencies with ivy">
		<ivy:retrieve pattern="lib/[conf]/[artifact]-[type]-[revision].[ext]" />
	</target>

	<target name="classpaths" depends="resolve">
		<path id="compile.classpath">
			<fileset dir="lib/compile" includes="*.jar" />
		</path>
	</target>

	<target name="init" depends="classpaths">
		<mkdir dir="build/classes" />
	</target>

	<target name="compile" depends="init" description="compile">
		<javac srcdir="src/main/java" destdir="build/classes" classpathref="compile.classpath" />
	</target>

	<target name="build" depends="compile">
		<spring-boot:exejar destfile="build/myapp.jar" classes="build/classes">
			<spring-boot:lib>
				<fileset dir="lib/runtime" />
			</spring-boot:lib>
		</spring-boot:exejar>
	</target>
</project>
----

TIP: If you do not want to use the `spring-boot-antlib` module, see the xref:how-to:build.adoc#howto.build.build-an-executable-archive-with-ant-without-using-spring-boot-antlib[] section of "`How-to Guides`".

[[using.build-systems.starters]]
== Starters
Starters are a set of convenient dependency descriptors that you can include in your application.
You get a one-stop shop for all the Spring and related technologies that you need without having to hunt through sample code and copy-paste loads of dependency descriptors.
For example, if you want to get started using Spring and JPA for database access, include the `spring-boot-starter-data-jpa` dependency in your project.

The starters contain a lot of the dependencies that you need to get a project up and running quickly and with a consistent, supported set of managed transitive dependencies.

.What is in a name
****
All **official** starters follow a similar naming pattern; `+spring-boot-starter-*+`, where `+*+` is a particular type of application.
This naming structure is intended to help when you need to find a starter.
The Maven integration in many IDEs lets you search dependencies by name.
For example, with the appropriate Eclipse or Spring Tools plugin installed, you can press `ctrl-space` in the POM editor and type "`spring-boot-starter`" for a complete list.

As explained in the xref:features/developing-auto-configuration.adoc#features.developing-auto-configuration.custom-starter[] section, third party starters should not start with `spring-boot`, as it is reserved for official Spring Boot artifacts.
Rather, a third-party starter typically starts with the name of the project.
For example, a third-party starter project called `thirdpartyproject` would typically be named `thirdpartyproject-spring-boot-starter`.
****

The following application starters are provided by Spring Boot under the `org.springframework.boot` group:

.Spring Boot application starters
include::ROOT:partial$starters/application-starters.adoc[]

In addition to the application starters, the following starters can be used to add xref:how-to:actuator.adoc[production ready] features:

.Spring Boot production starters
include::ROOT:partial$starters/production-starters.adoc[]

Finally, Spring Boot also includes the following starters that can be used if you want to exclude or swap specific technical facets:

.Spring Boot technical starters
include::ROOT:partial$starters/technical-starters.adoc[]

To learn how to swap technical facets, please see the how-to documentation for xref:how-to:webserver.adoc#howto.webserver.use-another[swapping web server] and xref:how-to:logging.adoc#howto.logging.log4j[logging system].

TIP: For a list of additional community contributed starters, see the {code-spring-boot-latest}/spring-boot-project/spring-boot-starters/README.adoc[README file] in the `spring-boot-starters` module on GitHub.