= Spring Beans 和依赖注入
:encoding: utf-8
:numbered:

[[using.spring-beans-and-dependency-injection]]
== Spring Beans 和依赖注入
你可以自由使用任何标准的 Spring Framework 技术来定义你的 bean 及其注入的依赖项。
我们通常建议使用构造函数注入来连接依赖项，并使用 `javadoc:org.springframework.context.annotation.ComponentScan[format=annotation]` 来查找 bean。

如果你按照上述建议构建代码（将应用程序类放在顶级包中），则可以添加 `javadoc:org.springframework.context.annotation.ComponentScan[format=annotation]` 而不带任何参数，或者使用隐式包含它的 `javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation]` 注解。
你的所有应用程序组件（`@Component`、`javadoc:org.springframework.stereotype.Service[format=annotation]`、`javadoc:org.springframework.stereotype.Repository[format=annotation]`、`javadoc:org.springframework.stereotype.Controller[format=annotation]` 等）都会自动注册为 Spring Bean。

以下示例展示了一个使用构造函数注入来获取所需的 `RiskAssessor` bean 的 `javadoc:org.springframework.stereotype.Service[format=annotation]` Bean：

include-code::singleconstructor/MyAccountService[]

如果一个 bean 有多个构造函数，你需要使用 `javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation]` 标记你希望 Spring 使用的构造函数：

include-code::multipleconstructors/MyAccountService[]

TIP: 请注意，使用构造函数注入可以让 `riskAssessor` 字段标记为 `final`，表示它之后不能被更改。

'''
== Spring Beans and Dependency Injection
You are free to use any of the standard Spring Framework techniques to define your beans and their injected dependencies.
We generally recommend using constructor injection to wire up dependencies and javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] to find beans.

If you structure your code as suggested above (locating your application class in a top package), you can add javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] without any arguments or use the javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] annotation which implicitly includes it.
All of your application components (`@Component`, javadoc:org.springframework.stereotype.Service[format=annotation], javadoc:org.springframework.stereotype.Repository[format=annotation], javadoc:org.springframework.stereotype.Controller[format=annotation], and others) are automatically registered as Spring Beans.

The following example shows a javadoc:org.springframework.stereotype.Service[format=annotation] Bean that uses constructor injection to obtain a required `RiskAssessor` bean:

include-code::singleconstructor/MyAccountService[]

If a bean has more than one constructor, you will need to mark the one you want Spring to use with javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation]:

include-code::multipleconstructors/MyAccountService[]

TIP: Notice how using constructor injection lets the `riskAssessor` field be marked as `final`, indicating that it cannot be subsequently changed.
