= Using the CLI
:encoding: utf-8
:numbered:

[[cli.using-the-cli]]
== 使用 CLI

安装 CLI 后，你可以在命令行中输入 `spring` 并按回车键来运行它。如果你不带任何参数运行 `spring`，则会显示帮助屏幕，如下所示：

[source,shell]
----
$ spring
usage: spring [--help] [--version]
       <command> [<args>]

可用的命令有：

  init [options] [location]
    使用 Spring Initializr (start.spring.io) 初始化一个新项目

  encodepassword [options] <要编码的密码>
    为 Spring Security 编码密码

  shell
    启动一个嵌套的 shell

常用选项：

  --debug 详细模式
    打印正在运行的命令的额外状态信息


有关特定命令的更多信息，请参阅 'spring help <command>'。
----

你可以输入 `spring help` 来获取有关任何支持命令的更多详细信息，如下例所示：

[source,shell]
----
$ spring help init
spring init - 使用 Spring Initializr (start.spring.io) 初始化一个新项目

用法: spring init [options] [location]

选项                       描述
------                    -----------
-a, --artifact-id <String>   项目坐标；推断归档名称（例如 'test'）
-b, --boot-version <String>  Spring Boot 版本（例如 '1.2.0.RELEASE'）
--build <String>             使用的构建系统（例如 'maven' 或 'gradle'）（默认：maven）
-d, --dependencies <String>  逗号分隔的依赖项标识符列表，包含在生成的项目中
--description <String>       项目描述
-f, --force                  强制覆盖现有文件
--format <String>            生成内容的格式（例如 'build' 表示构建文件，'project' 表示项目归档）（默认：project）
-g, --group-id <String>      项目坐标（例如 'org.test'）
-j, --java-version <String>  语言级别（例如 '1.8'）
-l, --language <String>      编程语言（例如 'java'）
--list                       列出服务的功能。用于发现可用的依赖项和类型
-n, --name <String>          项目名称；推断应用程序名称
-p, --packaging <String>     项目打包方式（例如 'jar'）
--package-name <String>      包名
-t, --type <String>          项目类型。如果使用 --build 和/或 --format，通常不需要。检查服务的功能（--list）以获取更多详细信息
--target <String>            使用的服务 URL（默认：https://start.spring.io）
-v, --version <String>       项目版本（例如 '0.0.1-SNAPSHOT'）
-x, --extract                提取项目归档。如果指定了没有扩展名的位置，则推断

示例：

    列出服务的所有功能：
        $ spring init --list

    创建一个默认项目：
        $ spring init

    创建一个 web 项目的 my-app.zip：
        $ spring init -d=web my-app.zip

    创建一个 web/data-jpa 的 gradle 项目并解压：
        $ spring init -d=web,jpa --build=gradle my-dir
----

`version` 命令提供了一种快速检查你正在使用的 Spring Boot 版本的方法，如下所示：

[source,shell,subs="verbatim,attributes"]
----
$ spring version
Spring CLI v{version-spring-boot}
----

[[cli.using-the-cli.initialize-new-project]]
== 初始化新项目

`init` 命令允许你使用 https://start.spring.io 创建一个新项目，而无需离开 shell，如下例所示：

[source,shell]
----
$ spring init --dependencies=web,data-jpa my-project
Using service at https://start.spring.io
Project extracted to '/Users/developer/example/my-project'
----

前面的示例创建了一个 `my-project` 目录，其中包含一个基于 Maven 的项目，该项目使用 `spring-boot-starter-web` 和 `spring-boot-starter-data-jpa`。你可以使用 `--list` 标志列出服务的功能，如下例所示：

[source,shell]
----
$ spring init --list
=======================================
Capabilities of https://start.spring.io
=======================================

可用的依赖项：
-----------------------
actuator - Actuator: 生产就绪功能，帮助你监控和管理应用程序
...
web - Web: 支持全栈 Web 开发，包括 Tomcat 和 spring-webmvc
websocket - Websocket: 支持 WebSocket 开发
ws - WS: 支持 Spring Web Services

可用的项目类型：
------------------------
gradle-build -  Gradle 配置 [format:build, build:gradle]
gradle-project -  Gradle 项目 [format:project, build:gradle]
maven-build -  Maven POM [format:build, build:maven]
maven-project -  Maven 项目 [format:project, build:maven] (默认)

...
----

`init` 命令支持许多选项。有关更多详细信息，请参阅 `help` 输出。例如，以下命令创建了一个使用 Java 17 和 `war` 打包的 Gradle 项目：

[source,shell]
----
$ spring init --build=gradle --java-version=17 --dependencies=websocket --packaging=war sample-app.zip
Using service at https://start.spring.io
Content saved to 'sample-app.zip'
----

[[cli.using-the-cli.embedded-shell]]
== 使用嵌入式 Shell

Spring Boot 包含适用于 BASH 和 zsh shell 的命令行补全脚本。如果你不使用这些 shell（可能是 Windows 用户），可以使用 `shell` 命令启动一个集成的 shell，如下例所示：

[source,shell,subs="verbatim,quotes,attributes"]
----
$ spring shell
*Spring Boot* (v{version-spring-boot})
按 TAB 键补全。输入 'help' 并按回车键获取帮助，输入 'exit' 退出。
----

在嵌入式 shell 中，你可以直接运行其他命令：

[source,shell,subs="verbatim,attributes"]
----
$ version
Spring CLI v{version-spring-boot}
----

嵌入式 shell 支持 ANSI 颜色输出以及 `tab` 补全。如果需要运行本地命令，可以使用 `!` 前缀。要退出嵌入式 shell，请按 `ctrl-c`。

'''
[[cli.using-the-cli]]
== Using the CLI
Once you have installed the CLI, you can run it by typing `spring` and pressing Enter at the command line.
If you run `spring` without any arguments, a help screen is displayed, as follows:

[source,shell]
----
$ spring
usage: spring [--help] [--version]
       <command> [<args>]

Available commands are:

  init [options] [location]
    Initialize a new project using Spring Initializr (start.spring.io)

  encodepassword [options] <password to encode>
    Encode a password for use with Spring Security

  shell
    Start a nested shell

Common options:

  --debug Verbose mode
    Print additional status information for the command you are running


See 'spring help <command>' for more information on a specific command.
----

You can type `spring help` to get more details about any of the supported commands, as shown in the following example:

[source,shell]
----
$ spring help init
spring init - Initialize a new project using Spring Initializr (start.spring.io)

usage: spring init [options] [location]

Option                       Description
------                       -----------
-a, --artifact-id <String>   Project coordinates; infer archive name (for
                               example 'test')
-b, --boot-version <String>  Spring Boot version (for example '1.2.0.RELEASE')
--build <String>             Build system to use (for example 'maven' or
                               'gradle') (default: maven)
-d, --dependencies <String>  Comma-separated list of dependency identifiers to
                               include in the generated project
--description <String>       Project description
-f, --force                  Force overwrite of existing files
--format <String>            Format of the generated content (for example
                               'build' for a build file, 'project' for a
                               project archive) (default: project)
-g, --group-id <String>      Project coordinates (for example 'org.test')
-j, --java-version <String>  Language level (for example '1.8')
-l, --language <String>      Programming language  (for example 'java')
--list                       List the capabilities of the service. Use it to
                               discover the dependencies and the types that are
                               available
-n, --name <String>          Project name; infer application name
-p, --packaging <String>     Project packaging (for example 'jar')
--package-name <String>      Package name
-t, --type <String>          Project type. Not normally needed if you use --
                               build and/or --format. Check the capabilities of
                               the service (--list) for more details
--target <String>            URL of the service to use (default: https://start.
                               spring.io)
-v, --version <String>       Project version (for example '0.0.1-SNAPSHOT')
-x, --extract                Extract the project archive. Inferred if a
                               location is specified without an extension

examples:

    To list all the capabilities of the service:
        $ spring init --list

    To creates a default project:
        $ spring init

    To create a web my-app.zip:
        $ spring init -d=web my-app.zip

    To create a web/data-jpa gradle project unpacked:
        $ spring init -d=web,jpa --build=gradle my-dir
----

The `version` command provides a quick way to check which version of Spring Boot you are using, as follows:

[source,shell,subs="verbatim,attributes"]
----
$ spring version
Spring CLI v{version-spring-boot}
----

[[cli.using-the-cli.initialize-new-project]]
== Initialize a New Project

The `init` command lets you create a new project by using https://start.spring.io without leaving the shell, as shown in the following example:

[source,shell]
----
$ spring init --dependencies=web,data-jpa my-project
Using service at https://start.spring.io
Project extracted to '/Users/developer/example/my-project'
----

The preceding example creates a `my-project` directory with a Maven-based project that uses `spring-boot-starter-web` and `spring-boot-starter-data-jpa`.
You can list the capabilities of the service by using the `--list` flag, as shown in the following example:

[source,shell]
----
$ spring init --list
=======================================
Capabilities of https://start.spring.io
=======================================

Available dependencies:
-----------------------
actuator - Actuator: Production ready features to help you monitor and manage your application
...
web - Web: Support for full-stack web development, including Tomcat and spring-webmvc
websocket - Websocket: Support for WebSocket development
ws - WS: Support for Spring Web Services

Available project types:
------------------------
gradle-build -  Gradle Config [format:build, build:gradle]
gradle-project -  Gradle Project [format:project, build:gradle]
maven-build -  Maven POM [format:build, build:maven]
maven-project -  Maven Project [format:project, build:maven] (default)

...
----

The `init` command supports many options.
See the `help` output for more details.
For instance, the following command creates a Gradle project that uses Java 17 and `war` packaging:

[source,shell]
----
$ spring init --build=gradle --java-version=17 --dependencies=websocket --packaging=war sample-app.zip
Using service at https://start.spring.io
Content saved to 'sample-app.zip'
----

[[cli.using-the-cli.embedded-shell]]
== Using the Embedded Shell
Spring Boot includes command-line completion scripts for the BASH and zsh shells.
If you do not use either of these shells (perhaps you are a Windows user), you can use the `shell` command to launch an integrated shell, as shown in the following example:

[source,shell,subs="verbatim,quotes,attributes"]
----
$ spring shell
*Spring Boot* (v{version-spring-boot})
Hit TAB to complete. Type \'help' and hit RETURN for help, and \'exit' to quit.
----

From inside the embedded shell, you can run other commands directly:

[source,shell,subs="verbatim,attributes"]
----
$ version
Spring CLI v{version-spring-boot}
----

The embedded shell supports ANSI color output as well as `tab` completion.
If you need to run a native command, you can use the `!` prefix.
To exit the embedded shell, press `ctrl-c`.