= Spring Boot

image:https://github.com/spring-projects/spring-boot/actions/workflows/build-and-deploy-snapshot.yml/badge.svg?branch=main["Build Status", link="https://github.com/spring-projects/spring-boot/actions/workflows/build-and-deploy-snapshot.yml?query=branch%3Amain"]
image:https://img.shields.io/badge/Revved%20up%20by-Develocity-06A0CE?logo=Gradle&labelColor=02303A["Revved up by Develocity", link="https://ge.spring.io/scans?&search.rootProjectNames=Spring%20Boot%20Build&search.rootProjectNames=spring-boot-build"]

:docs: https://docs.spring.io/spring-boot
:github: https://github.com/spring-projects/spring-boot

Spring Boot helps you create production-grade Spring-powered applications with minimal configuration.

It provides a set of defaults and auto-configurations so that new and existing users can focus on business logic rather than boilerplate code.

== Getting Started

The {docs}[reference documentation] includes detailed installation instructions and a comprehensive {docs}/tutorial/first-application/index.html[getting started guide].

Here's a simple Spring Boot application in Java:

[source,java]
----
import org.springframework.boot.*;
import org.springframework.boot.autoconfigure.*;
import org.springframework.web.bind.annotation.*;

@RestController
@SpringBootApplication
public class Example {

    @RequestMapping("/")
    String home() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SpringApplication.run(Example.class, args);
    }
}
----

== Want to Contribute?

We welcome contributions of all kinds!

If you're new, check out our https://github.com/spring-projects/spring-boot/blob/main/CONTRIBUTING.adoc[Contributing Guide] and look for issues labeled https://github.com/spring-projects/spring-boot/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22["good first issue"].

You can also:
* Improve documentation
* Help test or reproduce bugs
* Add sample projects or fix typos

== Community and Support

Need help or have questions?

* 📚 Check the {docs}/how-to/index.html[How-to Guides]
* 💬 Join the https://spring.io/slack[Spring Community Slack]
* 💡 Explore https://spring.io/guides[Spring Guides]
* ❓ Ask on StackOverflow with the tag https://stackoverflow.com/questions/tagged/spring-boot[`spring-boot`]

== License

Spring Boot is Open Source software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].

