= Getting support for Spring Boot

== GitHub issues
We choose not use GitHub issues for general usage questions and support, preferring to
use issues solely for the tracking of bugs and enhancements. If you have a general
usage question please do not open a GitHub issue, but use one of the other channels
described below.

If you are reporting a bug, please help to speed up problem diagnosis by providing as
much information as possible. Ideally, that would include a small
https://github.com/spring-projects/spring-boot-issues[sample project] that reproduces the
problem.

== Stack Overflow
The Spring Boot community monitors the
https://stackoverflow.com/tags/spring-boot[`spring-boot`] tag on Stack Overflow. Before
asking a question, please familiar yourself with Stack Overflow's
https://stackoverflow.com/help/how-to-ask[advice on how to ask a good question].

== Gitter
If you want to discuss something or have a question that isn't suited to Stack Overflow,
the Spring Boot community chat in the
https://gitter.im/spring-projects/spring-boot[#spring-boot room on Gitter].

== Pivotal Open Source Software Support
If you are interested in more dedicated support, Pivotal provides
https://pivotal.io/support/oss[premium support] for Spring Boot.
