= 提前处理
:encoding: utf-8
:numbered:

[[howto.aot]]
== 提前处理
人们在使用 Spring Boot 应用程序的提前处理时经常会遇到一些问题。本节将解决这些问题。

[[howto.aot.conditions]]
== 条件
提前处理会优化应用程序，并根据构建时的环境评估 javadoc:org.springframework.context.annotation.Conditional[format=annotation] 注解。xref:reference:features/profiles.adoc[配置文件] 通过条件实现，因此也会受到影响。

如果你希望在提前优化的应用程序中创建基于条件的 bean，你必须在构建应用程序时设置环境。在构建时提前处理期间创建的 bean 在运行应用程序时总是会被创建，并且无法关闭。为此，你可以设置在构建应用程序时应使用的配置文件。

对于 Maven，可以通过设置 `spring-boot-maven-plugin:process-aot` 执行的 `profiles` 配置来实现：

[source,xml]
----
<profile>
    <id>native</id>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>process-aot</id>
                            <configuration>
                                <profiles>profile-a,profile-b</profiles>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</profile>
----

对于 Gradle，你需要配置 `ProcessAot` 任务：

[source,gradle]
----
tasks.withType(org.springframework.boot.gradle.tasks.aot.ProcessAot).configureEach {
    args('--spring.profiles.active=profile-a,profile-b')
}
----

在运行提前优化的应用程序时，仅更改不影响条件的配置属性的配置文件不受限制。

'''
[[howto.aot]]
== Ahead-of-Time Processing
A number of questions often arise when people use the ahead-of-time processing of Spring Boot applications.
This section addresses those questions.

[[howto.aot.conditions]]
== Conditions
Ahead-of-time processing optimizes the application and evaluates javadoc:org.springframework.context.annotation.Conditional[format=annotation] annotations based on the environment at build time.
xref:reference:features/profiles.adoc[Profiles] are implemented through conditions and are therefore affected, too.

If you want beans that are created based on a condition in an ahead-of-time optimized application, you have to set up the environment when building the application.
The beans which are created while ahead-of-time processing at build time are then always created when running the application and can't be switched off.
To do this, you can set the profiles which should be used when building the application.

For Maven, this works by setting the `profiles` configuration of the `spring-boot-maven-plugin:process-aot` execution:

[source,xml]
----
<profile>
    <id>native</id>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>process-aot</id>
                            <configuration>
                                <profiles>profile-a,profile-b</profiles>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</profile>
----

For Gradle, you need to configure the `ProcessAot` task:

[source,gradle]
----
tasks.withType(org.springframework.boot.gradle.tasks.aot.ProcessAot).configureEach {
    args('--spring.profiles.active=profile-a,profile-b')
}
----

Profiles which only change configuration properties that don't influence conditions are supported without limitations when running ahead-of-time optimized applications.
