= 批处理应用程序
:encoding: utf-8
:numbered:

[[howto.batch]]
== 批处理应用程序
人们在使用 Spring Boot 应用程序中的 Spring Batch 时经常会遇到一些问题。本节将解决这些问题。

[[howto.batch.specifying-a-data-source]]
== 指定批处理数据源
默认情况下，批处理应用程序需要一个 javadoc:javax.sql.DataSource[] 来存储作业详细信息。Spring Batch 默认期望一个单一的 javadoc:javax.sql.DataSource[]。要让它使用应用程序主 javadoc:javax.sql.DataSource[] 以外的数据源，请声明一个 javadoc:javax.sql.DataSource[] bean，并使用 javadoc:org.springframework.boot.autoconfigure.batch.BatchDataSource[format=annotation] 注解其 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法。如果你这样做并希望有两个数据源（例如保留主自动配置的 javadoc:javax.sql.DataSource[]），请将 javadoc:org.springframework.context.annotation.Bean[format=annotation] 注解的 `defaultCandidate` 属性设置为 `false`。为了获得更大的控制权，请将 javadoc:org.springframework.batch.core.configuration.annotation.EnableBatchProcessing[format=annotation] 添加到你的一个 javadoc:org.springframework.context.annotation.Configuration[format=annotation] 类中，或扩展 javadoc:org.springframework.batch.core.configuration.support.DefaultBatchConfiguration[]。有关更多详细信息，请参阅 javadoc:org.springframework.batch.core.configuration.annotation.EnableBatchProcessing[format=annotation] 和 javadoc:org.springframework.batch.core.configuration.support.DefaultBatchConfiguration[] 的 API 文档。

有关 Spring Batch 的更多信息，请参阅 {url-spring-batch-site}[Spring Batch 项目页面]。

[[howto.batch.specifying-a-transaction-manager]]
== 指定批处理事务管理器
与 xref:batch.adoc#howto.batch.specifying-a-data-source[] 类似，你可以通过使用 javadoc:org.springframework.boot.autoconfigure.batch.BatchTransactionManager[format=annotation] 注解其 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法来定义一个用于批处理的 javadoc:org.springframework.transaction.PlatformTransactionManager[]。如果你这样做并希望有两个事务管理器（例如保留自动配置的 javadoc:org.springframework.transaction.PlatformTransactionManager[]），请将 javadoc:org.springframework.context.annotation.Bean[format=annotation] 注解的 `defaultCandidate` 属性设置为 `false`。

[[howto.batch.specifying-a-task-executor]]
== 指定批处理任务执行器
与 xref:batch.adoc#howto.batch.specifying-a-data-source[] 类似，你可以通过使用 javadoc:org.springframework.boot.autoconfigure.batch.BatchTaskExecutor[format=annotation] 注解其 javadoc:org.springframework.context.annotation.Bean[format=annotation] 方法来定义一个用于批处理的 javadoc:org.springframework.core.task.TaskExecutor[]。如果你这样做并希望有两个任务执行器（例如保留自动配置的 javadoc:org.springframework.core.task.TaskExecutor[]），请将 javadoc:org.springframework.context.annotation.Bean[format=annotation] 注解的 `defaultCandidate` 属性设置为 `false`。

[[howto.batch.running-jobs-on-startup]]
== 在启动时运行 Spring Batch 作业
通过将 `spring-boot-starter-batch` 添加到应用程序的类路径中，可以启用 Spring Batch 自动配置。

如果在应用程序上下文中找到单个 javadoc:org.springframework.batch.core.Job[] bean，它将在启动时执行（有关详细信息，请参阅 javadoc:org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner[]）。如果找到多个 javadoc:org.springframework.batch.core.Job[] bean，则必须使用 configprop:spring.batch.job.name[] 指定应执行的作业。

要禁用运行在应用程序上下文中找到的 javadoc:org.springframework.batch.core.Job[]，请将 configprop:spring.batch.job.enabled[] 设置为 `false`。

有关更多详细信息，请参阅 {code-spring-boot-autoconfigure-src}/batch/BatchAutoConfiguration.java[`BatchAutoConfiguration`]。

[[howto.batch.running-from-the-command-line]]
== 从命令行运行
Spring Boot 将以 `--` 开头的任何命令行参数转换为要添加到 javadoc:org.springframework.core.env.Environment[] 的属性，请参阅 xref:reference:features/external-config.adoc#features.external-config.command-line-args[访问命令行属性]。这不应用于将参数传递给批处理作业。要在命令行上指定批处理参数，请使用常规格式（即不带 `--`），如下例所示：

[source,shell]
----
$ java -jar myapp.jar someParameter=someValue anotherParameter=anotherValue
----

如果你在命令行上指定了 javadoc:org.springframework.core.env.Environment[] 的属性，作业将忽略它。考虑以下命令：

[source,shell]
----
$ java -jar myapp.jar --server.port=7070 someParameter=someValue
----

这仅向批处理作业提供一个参数：`someParameter=someValue`。

[[howto.batch.restarting-a-failed-job]]
== 重新启动已停止或失败的作业
要重新启动失败的 javadoc:org.springframework.batch.core.Job[]，必须在命令行上重新指定所有参数（标识性和非标识性）。非标识性参数不会从先前的执行中复制。这允许修改或删除它们。

NOTE: 当你使用自定义的 javadoc:org.springframework.batch.core.JobParametersIncrementer[] 时，你必须收集增量器管理的所有参数以重新启动失败的执行。

[[howto.batch.storing-job-repository]]
== 存储作业仓库
Spring Batch 需要一个数据存储来存储 javadoc:org.springframework.batch.core.Job[] 仓库。如果你使用 Spring Boot，则必须使用实际的数据库。请注意，它可以是内存数据库，请参阅 {url-spring-batch-docs}/job.html#configuringJobRepository[配置作业仓库]。

'''
[[howto.batch]]
== Batch Applications
A number of questions often arise when people use Spring Batch from within a Spring Boot application.
This section addresses those questions.

[[howto.batch.specifying-a-data-source]]
== Specifying a Batch Data Source
By default, batch applications require a javadoc:javax.sql.DataSource[] to store job details.
Spring Batch expects a single javadoc:javax.sql.DataSource[] by default.
To have it use a javadoc:javax.sql.DataSource[] other than the application’s main javadoc:javax.sql.DataSource[], declare a javadoc:javax.sql.DataSource[] bean, annotating its javadoc:org.springframework.context.annotation.Bean[format=annotation] method with javadoc:org.springframework.boot.autoconfigure.batch.BatchDataSource[format=annotation].
If you do so and want two data sources (for example by retaining the main auto-configured javadoc:javax.sql.DataSource[]), set the `defaultCandidate` attribute of the javadoc:org.springframework.context.annotation.Bean[format=annotation] annotation to `false`.
To take greater control, add javadoc:org.springframework.batch.core.configuration.annotation.EnableBatchProcessing[format=annotation] to one of your javadoc:org.springframework.context.annotation.Configuration[format=annotation] classes or extend javadoc:org.springframework.batch.core.configuration.support.DefaultBatchConfiguration[].
See the API documentation of javadoc:org.springframework.batch.core.configuration.annotation.EnableBatchProcessing[format=annotation]
and javadoc:org.springframework.batch.core.configuration.support.DefaultBatchConfiguration[] for more details.

For more info about Spring Batch, see the {url-spring-batch-site}[Spring Batch project page].

[[howto.batch.specifying-a-transaction-manager]]
== Specifying a Batch Transaction Manager
Similar to xref:batch.adoc#howto.batch.specifying-a-data-source[], you can define a javadoc:org.springframework.transaction.PlatformTransactionManager[] for use in batch processing by annotating its javadoc:org.springframework.context.annotation.Bean[format=annotation] method with javadoc:org.springframework.boot.autoconfigure.batch.BatchTransactionManager[format=annotation].
If you do so and want two transaction managers (for example by retaining the auto-configured javadoc:org.springframework.transaction.PlatformTransactionManager[]), set the `defaultCandidate` attribute of the javadoc:org.springframework.context.annotation.Bean[format=annotation] annotation to `false`.

[[howto.batch.specifying-a-task-executor]]
== Specifying a Batch Task Executor
Similar to xref:batch.adoc#howto.batch.specifying-a-data-source[], you can define a javadoc:org.springframework.core.task.TaskExecutor[] for use in batch processing by annotating its javadoc:org.springframework.context.annotation.Bean[format=annotation] method with javadoc:org.springframework.boot.autoconfigure.batch.BatchTaskExecutor[format=annotation].
If you do so and want two task executors (for example by retaining the auto-configured javadoc:org.springframework.core.task.TaskExecutor[]), set the `defaultCandidate` attribute of the javadoc:org.springframework.context.annotation.Bean[format=annotation] annotation to `false`.

[[howto.batch.running-jobs-on-startup]]
== Running Spring Batch Jobs on Startup
Spring Batch auto-configuration is enabled by adding `spring-boot-starter-batch` to your application's classpath.

If a single javadoc:org.springframework.batch.core.Job[] bean is found in the application context, it is executed on startup (see javadoc:org.springframework.boot.autoconfigure.batch.JobLauncherApplicationRunner[] for details).
If multiple javadoc:org.springframework.batch.core.Job[] beans are found, the job that should be executed must be specified using configprop:spring.batch.job.name[].

To disable running a javadoc:org.springframework.batch.core.Job[] found in the application context, set the configprop:spring.batch.job.enabled[] to `false`.

See {code-spring-boot-autoconfigure-src}/batch/BatchAutoConfiguration.java[`BatchAutoConfiguration`] for more details.

[[howto.batch.running-from-the-command-line]]
== Running From the Command Line
Spring Boot converts any command line argument starting with `--` to a property to add to the javadoc:org.springframework.core.env.Environment[], see xref:reference:features/external-config.adoc#features.external-config.command-line-args[accessing command line properties].
This should not be used to pass arguments to batch jobs.
To specify batch arguments on the command line, use the regular format (that is without `--`), as shown in the following example:

[source,shell]
----
$ java -jar myapp.jar someParameter=someValue anotherParameter=anotherValue
----

If you specify a property of the javadoc:org.springframework.core.env.Environment[] on the command line, it is ignored by the job.
Consider the following command:

[source,shell]
----
$ java -jar myapp.jar --server.port=7070 someParameter=someValue
----

This provides only one argument to the batch job: `someParameter=someValue`.

[[howto.batch.restarting-a-failed-job]]
== Restarting a Stopped or Failed Job
To restart a failed javadoc:org.springframework.batch.core.Job[], all parameters (identifying and non-identifying) must be re-specified on the command line.
Non-identifying parameters are *not* copied from the previous execution.
This allows them to be modified or removed.

NOTE: When you're using a custom javadoc:org.springframework.batch.core.JobParametersIncrementer[], you have to gather all parameters managed by the incrementer to restart a failed execution.

[[howto.batch.storing-job-repository]]
== Storing the Job Repository
Spring Batch requires a data store for the javadoc:org.springframework.batch.core.Job[] repository.
If you use Spring Boot, you must use an actual database.
Note that it can be an in-memory database, see {url-spring-batch-docs}/job.html#configuringJobRepository[Configuring a Job Repository].