= HTTP 客户端
:encoding: utf-8
:numbered:

[[howto.http-clients]]
== HTTP 客户端
Spring Boot 提供了多个与 HTTP 客户端相关的启动器。本节回答与使用它们相关的问题。

[[howto.http-clients.rest-template-proxy-configuration]]
== 配置 RestTemplate 以使用代理
如 [RestTemplate 自定义](xref:reference:io/rest-client.adoc#io.rest-client.resttemplate.customization) 中所述，你可以使用 `org.springframework.boot.web.client.RestTemplateCustomizer` 与 `org.springframework.boot.web.client.RestTemplateBuilder` 来构建自定义的 `org.springframework.web.client.RestTemplate`。这是创建配置为使用代理的 `org.springframework.web.client.RestTemplate` 的推荐方法。

代理配置的具体细节取决于所使用的底层客户端请求工厂。

[[howto.http-clients.webclient-reactor-netty-customization]]
== 配置基于 Reactor Netty 的 WebClient 使用的 TcpClient
当 Reactor Netty 在类路径上时，会自动配置基于 Reactor Netty 的 `org.springframework.web.reactive.function.client.WebClient`。要自定义客户端对网络连接的处理，请提供一个 `org.springframework.http.client.reactive.ClientHttpConnector` Bean。以下示例配置了 60 秒的连接超时并添加了一个 `io.netty.handler.timeout.ReadTimeoutHandler`：

```java
include-code::MyReactorNettyClientConfiguration[]
```

TIP: 注意使用 `org.springframework.http.client.ReactorResourceFactory` 来管理连接提供者和事件循环资源。这确保了接收请求的服务器和发出请求的客户端之间资源的高效共享。

'''
[[howto.http-clients]]
== HTTP Clients
Spring Boot offers a number of starters that work with HTTP clients.
This section answers questions related to using them.

[[howto.http-clients.rest-template-proxy-configuration]]
== Configure RestTemplate to Use a Proxy
As described in xref:reference:io/rest-client.adoc#io.rest-client.resttemplate.customization[RestTemplate Customization], you can use a javadoc:org.springframework.boot.web.client.RestTemplateCustomizer[] with javadoc:org.springframework.boot.web.client.RestTemplateBuilder[] to build a customized javadoc:org.springframework.web.client.RestTemplate[].
This is the recommended approach for creating a javadoc:org.springframework.web.client.RestTemplate[] configured to use a proxy.

The exact details of the proxy configuration depend on the underlying client request factory that is being used.

[[howto.http-clients.webclient-reactor-netty-customization]]
== Configure the TcpClient used by a Reactor Netty-based WebClient
When Reactor Netty is on the classpath a Reactor Netty-based javadoc:org.springframework.web.reactive.function.client.WebClient[] is auto-configured.
To customize the client's handling of network connections, provide a javadoc:org.springframework.http.client.reactive.ClientHttpConnector[] bean.
The following example configures a 60 second connect timeout and adds a javadoc:io.netty.handler.timeout.ReadTimeoutHandler[]:

include-code::MyReactorNettyClientConfiguration[]

TIP: Note the use of javadoc:org.springframework.http.client.ReactorResourceFactory[] for the connection provider and event loop resources.
This ensures efficient sharing of resources for the server receiving requests and the client making requests.
