[[index]]
= Spring Boot Reference Documentation
include::authors.adoc[]
v{spring-boot-version}
include::attributes.adoc[]



The reference documentation consists of the following sections:

[horizontal]
<<legal#legal,Legal>> :: Legal information.
<<documentation#documentation,Documentation Overview>> :: About the Documentation, Getting Help, First Steps, and more.
<<getting-started#getting-started,Getting Started>> :: Introducing Spring Boot, System Requirements, Servlet Containers, Installing Spring Boot, Developing Your First Spring Boot Application
<<using#using,Using Spring Boot>> :: Build Systems, Structuring Your Code, Configuration, Spring Beans and Dependency Injection, DevTools, and more.
<<features#features,Spring Boot Features>> :: Profiles, Logging, Security, Caching, Spring Integration, Testing, and more.
<<actuator#actuator,Spring Boot Actuator>> :: Monitoring, Metrics, Auditing, and more.
<<deployment#deployment,Deploying Spring Boot Applications>> :: Deploying to the Cloud, Installing as a Unix application.
<<cli#cli,Spring Boot CLI>> :: Installing the CLI, Using the CLI, Configuring the CLI, and more.
<<build-tool-plugins#build-tool-plugins,Build Tool Plugins>> :: Maven Plugin, Gradle Plugin, Antlib, and more.
<<howto#howto,"`How-to`" Guides>> :: Application Development, Configuration, Embedded Servers, Data Access, and many more.

The reference documentation has the following appendices:

[horizontal]
<<application-properties#application-properties,Application Properties>> :: Common application properties that can be used to configure your application.
<<configuration-metadata#configuration-metadata,Configuration Metadata>> :: Metadata used to describe configuration properties.
<<auto-configuration-classes#auto-configuration-classes,Auto-configuration Classes>> :: Auto-configuration classes provided by Spring Boot.
<<test-auto-configuration#test-auto-configuration,Test Auto-configuration Annotations>> :: Test auto-configuration annotations used to test slices of your application.
<<executable-jar#executable-jar,Executable Jars>> :: Spring Boot's executable jars, their launchers, and their format.
<<dependency-versions#dependency-versions,Dependency Versions>> :: Details of the dependencies that are managed by Spring Boot.
