<?xml version="1.0" encoding="UTF-8"?>
<project>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>aot-native-profile-buildpacks</artifactId>
	<profiles>
		<!-- tag::profile[] -->
		<profile>
			<id>native</id>
			<build>
				<pluginManagement>
					<plugins>
						<plugin>
							<groupId>org.springframework.boot</groupId>
							<artifactId>spring-boot-maven-plugin</artifactId>
							<configuration>
								<image>
									<runImage>paketobuildpacks/ubuntu-resolute-run-tiny</runImage>
								</image>
							</configuration>
							<executions>
								<execution>
									<id>build-image</id>
									<goals>
										<goal>build-image-no-fork</goal>
									</goals>
								</execution>
							</executions>
						</plugin>
					</plugins>
				</pluginManagement>
			</build>
		</profile>
		<!-- end::profile[] -->
	</profiles>

</project>


