= 社区
:encoding: utf-8
:numbered:

[[community]]
== 社区
如果你在使用 Spring Boot 时遇到问题，我们很乐意为你提供帮助。

* 尝试查阅 xref:how-to:index.adoc[操作指南文档]。
这些文档提供了针对最常见问题的解决方案。
* 学习 Spring 基础知识。
Spring Boot 是基于许多其他 Spring 项目构建的。
你可以访问 https://spring.io[spring.io] 网站，获取丰富的参考文档。
如果你是 Spring 的初学者，可以尝试学习 https://spring.io/guides[指南] 中的内容。
* 提出问题。
我们会在 https://stackoverflow.com[stackoverflow.com] 上关注带有 https://stackoverflow.com/tags/spring-boot[`spring-boot`] 标签的问题。
* 在 https://github.com/spring-projects/spring-boot/issues 上报告 Spring Boot 的 bug。

NOTE: Spring Boot 的所有内容都是开源的，包括文档。
如果你发现文档存在问题或希望改进文档，请 {url-github}[参与贡献]。

'''

== Community
If you have trouble with Spring Boot, we would like to help.

* Try the xref:how-to:index.adoc[How-to documents].
They provide solutions to the most common questions.
* Learn the Spring basics.
Spring Boot builds on many other Spring projects.
Check the https://spring.io[spring.io] web-site for a wealth of reference documentation.
If you are starting out with Spring, try one of the https://spring.io/guides[guides].
* Ask a question.
We monitor https://stackoverflow.com[stackoverflow.com] for questions tagged with https://stackoverflow.com/tags/spring-boot[`spring-boot`].
* Report bugs with Spring Boot at https://github.com/spring-projects/spring-boot/issues.

NOTE: All of Spring Boot is open source, including the documentation.
If you find problems with the docs or if you want to improve them, please {url-github}[get involved].
