/*
 * Copyright 2012-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.boot.configurationprocessor.ksp

import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import org.springframework.boot.configurationprocessor.ConfigurationMetadataGenerator

/**
 * [SymbolProcessor] that writes the meta-data file for `@ConfigurationProperties`.
 *
 * The symbols are adapted to the model that the [ConfigurationMetadataGenerator] works
 * with, so that the meta-data is generated by the code that the Java annotation processor
 * relies upon.
 *
 * @author Areg Iazychian
 */
internal class ConfigurationMetadataSymbolProcessor(environment: SymbolProcessorEnvironment) : SymbolProcessor {

	private val context = KspProcessingContext(environment)

	private val generator = ConfigurationMetadataGenerator(this.context)

	override fun process(resolver: Resolver): List<KSAnnotated> {
		this.context.resolver = resolver
		this.generator.process(KspProcessingRound(this.context, resolver))
		return emptyList()
	}

	override fun finish() {
		this.generator.writeSourceMetadata()
		this.generator.writeMetadata()
	}

}
