/*
 * Copyright 2012-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.boot.configurationprocessor.ksp

import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFile
import org.springframework.boot.configurationprocessor.ProcessingContext
import org.springframework.boot.configurationprocessor.model.AnnotationReference
import org.springframework.boot.configurationprocessor.model.Declaration
import org.springframework.boot.configurationprocessor.model.TypeDeclaration
import java.io.File
import java.io.FileNotFoundException
import java.io.InputStream
import java.io.OutputStream

/**
 * [ProcessingContext] backed by a [SymbolProcessorEnvironment].
 *
 * @author Areg Iazychian
 */
internal class KspProcessingContext(private val environment: SymbolProcessorEnvironment) : ProcessingContext {

	private val sourceFiles = LinkedHashSet<KSFile>()

	/**
	 * The resolver of the round that is being processed.
	 */
	lateinit var resolver: Resolver

	/**
	 * Return the [TypeDeclaration] of the given [declaration], recording its source file as
	 * one that the generated meta-data depends on.
	 */
	fun type(declaration: KSClassDeclaration): KspTypeDeclaration {
		declaration.containingFile?.let(this.sourceFiles::add)
		return KspTypeDeclaration(this, declaration)
	}

	override fun getTypeDeclaration(name: String): TypeDeclaration? =
		this.resolver.getClassDeclarationByName(name)?.let(::type)

	override fun getOptions(): Map<String, String> = this.environment.options

	override fun error(message: String, declaration: Declaration?, annotation: AnnotationReference?) {
		this.environment.logger.error(message, (declaration as? KspDeclaration)?.symbol)
	}

	override fun warn(message: String) {
		this.environment.logger.warn(message)
	}

	// KSP removes the files that have been generated by a previous build
	override fun openResource(location: String): InputStream = throw FileNotFoundException(location)

	override fun createResource(location: String): OutputStream {
		val dependencies = Dependencies(true, *this.sourceFiles.toTypedArray())
		val path = location.substringBeforeLast('.')
		return this.environment.codeGenerator.createNewFileByPath(dependencies, path, location.substringAfterLast('.'))
	}

	// KSP gives no access to the resources of the module
	override fun openAdditionalMetadata(location: String): InputStream =
		this.environment.options[ADDITIONAL_METADATA_LOCATIONS_OPTION].orEmpty()
			.split(",")
			.map { File(it, location) }
			.firstOrNull(File::isFile)
			?.inputStream() ?: throw FileNotFoundException(location)

	// KSP gives no access to the resources of the classpath
	override fun openClasspathResource(location: String): InputStream = throw FileNotFoundException(location)

	private companion object {

		private const val ADDITIONAL_METADATA_LOCATIONS_OPTION =
			"org.springframework.boot.configurationprocessor.additionalMetadataLocations"

	}

}
