[[integrating-with-actuator]]
== Integrating with Actuator

[[integrating-with-actuator-bundled-library-details]]
=== Generating Bundled Library Details
Spring Boot Actuator's `libraries` endpoint publishes details about the libraries bundled within the archive if a `META-INF/bundled-libraries.yaml` file is present.
The plugin's <<repackage,repackage goal>> generates this file based on the libraries bundled in the archive.

[[integrating-with-actuator-build-info]]
=== Generating Build Information
Spring Boot Actuator's `info` endpoint automatically publishes information about your build if a `META-INF/build-info.properties` file is present.
The `build-info` goal generates this file with the coordinates of the project and the build time.
It also allows you to add an arbitrary number of additional properties, as shown in the following example:

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<project>
		<build>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<executions>
						<execution>
							<goals>
								<goal>build-info</goal>
							</goals>
							<configuration>
								<additionalProperties>
									<encoding.source>UTF-8</encoding.source>
									<encoding.reporting>UTF-8</encoding.reporting>
									<java.source>${maven.compiler.source}</java.source>
									<java.target>${maven.compiler.target}</java.target>
								</additionalProperties>
							</configuration>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</build>
	</project>
----

This configuration will generate a `build-info.properties` at the expected location with four additional keys.

NOTE: `maven.compiler.source` and `maven.compiler.target` are expected to be regular properties available in the project.
They will be interpolated as you would expect.

include::goals/build-info.adoc[leveloffset=+2]
