= Starter POMs

Spring Boot Starters are a set of convenient dependency descriptors that you can include
in your application. You get a one-stop-shop for all the Spring and related technology
that you need without having to hunt through sample code and copy paste loads of
dependency descriptors. For example, if you want to get started using Spring and
JPA for database access just include the `spring-boot-starter-data-jpa` dependency in
your project, and you are good to go.

For complete details see the
http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#using-boot-starter-poms[reference documentation]

== Community Contributions
If you create a starter for a technology that is not already in the standard list we can
list it here. Just send a pull request for this page.

|===
| Name | Location

| https://code.google.com/p/wro4j/[WRO4J]
| https://github.com/sbuettner/spring-boot-autoconfigure-wro4j

| http://projects.spring.io/spring-batch/[Spring Batch] (Advanced usage)
| https://github.com/codecentric/spring-boot-starter-batch-web

| http://hdiv.org/[HDIV]
| https://github.com/hdiv/spring-boot-starter-hdiv

| https://github.com/neuland/jade4j[Jade Templates] (Jade4J)
| https://github.com/domix/spring-boot-starter-jade4j
|===
