services:
  rabbitmq:
    image: '{imageName}'
    environment:
      - 'RABBITMQ_DEFAULT_USER=myuser'
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_VHOST=app'
    ports:
      - '5672'
