stream.listeners.ssl.1 = 5551

ssl_options.cacertfile=/etc/rabbitmq/ca.crt
ssl_options.certfile=/etc/rabbitmq/server.crt
ssl_options.keyfile=/etc/rabbitmq/server.key

ssl_options.verify=verify_peer
ssl_options.fail_if_no_peer_cert=true
