= 审计
:encoding: utf-8
:numbered:

[[actuator.auditing]]
== 审计
一旦 Spring Security 生效，Spring Boot Actuator 就提供了一个灵活的审计框架，用于发布事件（默认情况下是“`认证成功`”、“`失败`”和“`访问被拒绝`”异常）。此功能对于报告和基于认证失败实施锁定策略非常有用。

你可以通过在应用程序配置中提供一个类型为 javadoc:org.springframework.boot.actuate.audit.AuditEventRepository[] 的 bean 来启用审计。为了方便起见，Spring Boot 提供了一个 javadoc:org.springframework.boot.actuate.audit.InMemoryAuditEventRepository[]。javadoc:org.springframework.boot.actuate.audit.InMemoryAuditEventRepository[] 功能有限，我们建议仅在开发环境中使用它。对于生产环境，考虑创建你自己的替代 javadoc:org.springframework.boot.actuate.audit.AuditEventRepository[] 实现。

[[actuator.auditing.custom]]
== 自定义审计
要自定义发布的安全事件，你可以提供 javadoc:org.springframework.boot.actuate.security.AbstractAuthenticationAuditListener[] 和 javadoc:org.springframework.boot.actuate.security.AbstractAuthorizationAuditListener[] 的自定义实现。

你也可以将审计服务用于你自己的业务事件。为此，可以将 javadoc:org.springframework.boot.actuate.audit.AuditEventRepository[] bean 注入到你自己的组件中并直接使用它，或者通过 Spring 的 javadoc:org.springframework.context.ApplicationEventPublisher[]（通过实现 javadoc:org.springframework.context.ApplicationEventPublisherAware[]）发布一个 javadoc:org.springframework.boot.actuate.audit.listener.AuditApplicationEvent[]。

'''
[[actuator.auditing]]
== Auditing
Once Spring Security is in play, Spring Boot Actuator has a flexible audit framework that publishes events (by default, "`authentication success`", "`failure`" and "`access denied`" exceptions).
This feature can be very useful for reporting and for implementing a lock-out policy based on authentication failures.

You can enable auditing by providing a bean of type javadoc:org.springframework.boot.actuate.audit.AuditEventRepository[] in your application's configuration.
For convenience, Spring Boot offers an javadoc:org.springframework.boot.actuate.audit.InMemoryAuditEventRepository[].
javadoc:org.springframework.boot.actuate.audit.InMemoryAuditEventRepository[] has limited capabilities, and we recommend using it only for development environments.
For production environments, consider creating your own alternative javadoc:org.springframework.boot.actuate.audit.AuditEventRepository[] implementation.

[[actuator.auditing.custom]]
== Custom Auditing
To customize published security events, you can provide your own implementations of javadoc:org.springframework.boot.actuate.security.AbstractAuthenticationAuditListener[] and javadoc:org.springframework.boot.actuate.security.AbstractAuthorizationAuditListener[].

You can also use the audit services for your own business events.
To do so, either inject the javadoc:org.springframework.boot.actuate.audit.AuditEventRepository[] bean into your own components and use that directly or publish an javadoc:org.springframework.boot.actuate.audit.listener.AuditApplicationEvent[] with the Spring javadoc:org.springframework.context.ApplicationEventPublisher[] (by implementing javadoc:org.springframework.context.ApplicationEventPublisherAware[]).