/*
 * Copyright 2012-2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.boot.loader.tools.layer;

import java.util.Collections;
import java.util.List;
import java.util.function.Function;

import org.springframework.boot.loader.tools.Layer;
import org.springframework.util.Assert;

/**
 * {@link ContentSelector} backed by {@code include}/{@code exclude} {@link ContentFilter
 * filters}.
 *
 * @param <T> the content type
 * @author Madhura Bhave
 * @author Phillip Webb
 * @since 2.3.0
 */
public class IncludeExcludeContentSelector<T> implements ContentSelector<T> {

	private final Layer layer;

	private final List<ContentFilter<T>> includes;

	private final List<ContentFilter<T>> excludes;

	/**
	 * Constructs a new IncludeExcludeContentSelector with the specified layer, includes,
	 * excludes, and identity function.
	 * @param layer the layer to apply the content selection on
	 * @param includes the list of content filters to include
	 * @param excludes the list of content filters to exclude
	 */
	public IncludeExcludeContentSelector(Layer layer, List<ContentFilter<T>> includes,
			List<ContentFilter<T>> excludes) {
		this(layer, includes, excludes, Function.identity());
	}

	public <S> IncludeExcludeContentSelector(Layer layer, List<S> includes, List<S> excludes,
			Function<S, ContentFilter<T>> filterFactory) {
		Assert.notNull(layer, "Layer must not be null");
		Assert.notNull(filterFactory, "FilterFactory must not be null");
		this.layer = layer;
		this.includes = (includes != null) ? adapt(includes, filterFactory) : Collections.emptyList();
		this.excludes = (excludes != null) ? adapt(excludes, filterFactory) : Collections.emptyList();
	}

	/**
	 * Adapts a list of objects of type S to a list of ContentFilter objects of type T
	 * using a mapper function.
	 * @param <S> the type of objects in the input list
	 * @param <T> the type of objects in the output list
	 * @param list the input list of objects to be adapted
	 * @param mapper the mapper function to convert each object in the input list to a
	 * ContentFilter object
	 * @return a list of ContentFilter objects generated by applying the mapper function
	 * to each object in the input list
	 */
	private <S> List<ContentFilter<T>> adapt(List<S> list, Function<S, ContentFilter<T>> mapper) {
		return list.stream().map(mapper).toList();
	}

	/**
	 * Returns the layer associated with this IncludeExcludeContentSelector.
	 * @return the layer associated with this IncludeExcludeContentSelector
	 */
	@Override
	public Layer getLayer() {
		return this.layer;
	}

	/**
	 * Checks if the specified item is contained in the content selector.
	 * @param item the item to be checked
	 * @return true if the item is contained in the content selector, false otherwise
	 */
	@Override
	public boolean contains(T item) {
		return isIncluded(item) && !isExcluded(item);
	}

	/**
	 * Checks if the specified item is included based on the content filters.
	 * @param item the item to check
	 * @return true if the item is included, false otherwise
	 */
	private boolean isIncluded(T item) {
		if (this.includes.isEmpty()) {
			return true;
		}
		for (ContentFilter<T> include : this.includes) {
			if (include.matches(item)) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Checks if the given item is excluded based on the content filters.
	 * @param item the item to be checked
	 * @return true if the item is excluded, false otherwise
	 */
	private boolean isExcluded(T item) {
		if (this.excludes.isEmpty()) {
			return false;
		}
		for (ContentFilter<T> exclude : this.excludes) {
			if (exclude.matches(item)) {
				return true;
			}
		}
		return false;
	}

}
