package org.springframework.boot.actuate.info;

import java.util.Properties;

import org.springframework.boot.bind.PropertiesConfigurationFactory;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PropertiesLoaderUtils;

/**
 * A {@link InfoProvider} that provides git information extracted from the git.properties file generated by the maven plugin
 * pl.project13.maven:git-commit-id-plugin.
 * 
 * @author Meang Akira Tanaka
 * @since 1.3.0
 */
public class ScmGitPropertiesInfoProvider implements InfoProvider {

	private final Resource gitPropertiesResource;
	private final GitInfo gitInfo;

	public ScmGitPropertiesInfoProvider(Resource gitPropertiesResource) throws Exception {
		this.gitPropertiesResource = gitPropertiesResource;
		gitInfo = extractGitInfo();
	}

	@Override
	public String name() {
		return "git";
	}

	@Override
	public Info provide() {
		if(gitInfo == null) {
			return null;
		}
		
		Info result = new Info();
		
		result.put("branch", gitInfo.getBranch());
		result.put("commit", gitInfo.getCommit());
		
		return result;
	}

	
	private GitInfo extractGitInfo() throws Exception {
		PropertiesConfigurationFactory<GitInfo> factory = new PropertiesConfigurationFactory<GitInfo>(
				new GitInfo());
		factory.setTargetName("git");
		Properties properties = new Properties();
		if (this.gitPropertiesResource.exists()) {
			properties = PropertiesLoaderUtils.loadProperties(this.gitPropertiesResource);
		} else {
			return null;
		}
		factory.setProperties(properties);
		return factory.getObject();
	}


	public static class GitInfo {

		private String branch;

		private final Commit commit = new Commit();

		public String getBranch() {
			return this.branch;
		}

		public void setBranch(String branch) {
			this.branch = branch;
		}

		public Commit getCommit() {
			return this.commit;
		}

		public static class Commit {

			private String id;

			private String time;

			public String getId() {
				return this.id == null ? ""
						: (this.id.length() > 7 ? this.id.substring(0, 7) : this.id);
			}

			public void setId(String id) {
				this.id = id;
			}

			public String getTime() {
				return this.time;
			}

			public void setTime(String time) {
				this.time = time;
			}

		}

	}
}
