[[packaging.aot-cache]]
= AOT Cache
:page-aliases: class-data-sharing.adoc

AOT cache is a https://openjdk.org/jeps/483[JVM feature] that can help reduce the startup time and memory footprint of Java applications.

If you are not yet using Java 25 or above, you should read the sections about CDS.
CDS is the predecessor of AOT cache, but works similarly.

NOTE: Spring Boot supports both CDS and AOT cache, however, we recommend using the AOT cache whenever possible.



[[packaging.aot-cache.aot-cache]]
== AOT Cache

NOTE: Spring Boot supports the AOT cache for Java 25 and above.
If you're using an earlier version of Java, you have to use CDS instead.

To use the AOT cache feature, you should first perform a training run on your application in extracted form:

[source,shell]
----
$ java -Djarmode=tools -jar my-app.jar extract --destination application
$ cd application
$ java -XX:AOTCacheOutput=app.aot -Dspring.context.exit=onRefresh -jar my-app.jar
----

This creates an `app.aot` cache file that can be reused as long as the application is not updated and the same Java version is used.

To use the cache file, you need to add an extra parameter when starting the application:

[source,shell]
----
$ java -XX:AOTCache=app.aot -jar my-app.jar
----

NOTE: You have to use the cache file with the extracted form of the application, otherwise it has no effect.

If you want to know how to leverage AOT Cache with Buildpacks, take a look at the xref:how-to:aot-cache.adoc[AOT Cache How-to guide].

[[packaging.aot-cache.integration-tests]]
== Generating AOT Cache from Integration Tests

Spring Boot provides Maven and Gradle integration to generate the AOT cache from your integration test suite.
This approach leverages existing tests as the training workload, avoiding the need for a separate training run.

NOTE: This feature requires Java 25 or above.

To enable AOT cache recording, set the `spring-boot.aot-cache-record` property (Maven) or the `aotCacheRecord` option (Gradle):

[tabs]
======
Maven::
+
[source,xml,indent=0,subs="verbatim,attributes"]
----
<properties>
    <spring-boot.aot-cache-record>true</spring-boot.aot-cache-record>
</properties>
----

Gradle::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
bootBuildImage {
    aotCacheRecord = true
}
----
======

Cache recording only activates when the image build goals or tasks are in the execution plan.
See the Maven plugin and Gradle plugin documentation for the exact invocation details.

When enabled, the build plugin:

* Injects `-XX:AOTCacheOutput=<path>` into the test JVM arguments
* Writes the cache file to `target/aot-cache/application.aot` (Maven) or `build/aot-cache/application.aot` (Gradle)
* Bundles the cache file into the built image when it is present

The cache file can then be used in production:

[source,shell]
----
$ java -XX:AOTCache=application.aot -jar my-app.jar
----

NOTE: You have to use the cache file with the extracted form of the application, otherwise it has no effect.


[[packaging.aot-cache.cds]]
== CDS

NOTE: If you're using Java 25 or above, please use AOT cache instead of CDS.

To use CDS, you should first perform a training run on your application in extracted form:

[source,shell]
----
$ java -Djarmode=tools -jar my-app.jar extract --destination application
$ cd application
$ java -XX:ArchiveClassesAtExit=application.jsa -Dspring.context.exit=onRefresh -jar my-app.jar
----

This creates an `application.jsa` archive file that can be reused as long as the application is not updated.

To use the archive file, you need to add an extra parameter when starting the application:

[source,shell]
----
$ java -XX:SharedArchiveFile=application.jsa -jar my-app.jar
----

NOTE: You have to use the cache file with the extracted form of the application, otherwise it has no effect.

NOTE: For more details about CDS, refer to the https://docs.oracle.com/en/java/javase/17/vm/class-data-sharing.html[Class Data Sharing documentation of the JDK].
