=== /autoconfig
This endpoint is a report on the Spring Boot auto-configuration process that happened when
your application started up. It lists all the  `@Conditional` annotations that were
evaluated as the context started and in each case it gives an indication of if (and why)
the condition matched. A positive match results in a bean being included in the context,
and a negative result means the opposite (the bean's class may not even be loaded).

The report is split into 2 parts, positive matches first, and then negative. If the
context is a hierarchy, there is also a separate report on the parent context with the
same format (and recursively up to the top of the hierarchy).

NOTE: The report is actually about `@Conditional` evaluation not auto-configuration
per se, but most auto-configuration features use `@Conditional` heavily, so there is a lot
of overlap.

Example curl request:
include::{generated}/autoconfig/curl-request.adoc[]

Example HTTP request: [small]##link:../autoconfig[icon:external-link[role="silver"]]##
include::{generated}/autoconfig/http-request.adoc[]

Example HTTP response:
include::{generated}/autoconfig/http-response.adoc[]
