FROM ubuntu:jammy-20230624
RUN apt-get update && \
    apt-get install -y software-properties-common curl && \
    mkdir -p /opt/oraclejdk && \
    cd /opt/oraclejdk && \
    curl -L https://download.oracle.com/java/17/archive/jdk-17.0.8_linux-aarch64_bin.tar.gz | tar zx --strip-components=1
ENV JAVA_HOME /opt/oraclejdk
ENV PATH $JAVA_HOME/bin:$PATH
