= Packaging OCI Images
:encoding: utf-8
:numbered:

[[build-image]]
== 打包 OCI 镜像
该插件可以使用 https://buildpacks.io[Cloud Native Buildpacks] (CNB) 从 jar 或 war 文件创建 https://github.com/opencontainers/image-spec[OCI 镜像]。
可以使用 `bootBuildImage` 任务构建镜像。

NOTE: 出于安全原因，镜像以非 root 用户身份构建和运行。
有关更多详细信息，请参阅 {url-buildpacks-docs}/reference/spec/platform-api/#users[CNB 规范]。

当应用 `java` 或 `war` 插件时，任务会自动创建，并且是 {apiref-gradle-plugin-boot-build-image}[`BootBuildImage`] 的实例。

[[build-image.docker-daemon]]
== Docker 守护进程
`bootBuildImage` 任务需要访问 Docker 守护进程。
任务将检查本地 Docker CLI https://docs.docker.com/engine/reference/commandline/cli/#configuration-files[配置文件] 以确定当前的 https://docs.docker.com/engine/context/working-with-contexts/[上下文]，并使用上下文连接信息与 Docker 守护进程通信。
如果无法确定当前上下文或上下文没有连接信息，则任务将使用默认的本地连接。
这适用于所有支持平台上的 https://docs.docker.com/install/[Docker Engine]，无需配置。

可以通过设置环境变量来配置 `bootBuildImage` 任务以使用替代的本地或远程连接。
下表显示了环境变量及其值：

|===
| 环境变量 | 描述

| DOCKER_CONFIG
| 用于确定当前上下文的 Docker CLI https://docs.docker.com/engine/reference/commandline/cli/#configuration-files[配置文件] 的位置（默认为 `$HOME/.docker`）

| DOCKER_CONTEXT
| 应从 Docker CLI 配置文件中检索主机信息的 https://docs.docker.com/engine/context/working-with-contexts/[上下文] 名称（覆盖 `DOCKER_HOST`）

| DOCKER_HOST
| 包含 Docker 守护进程的主机和端口的 URL - 例如 `tcp://192.168.99.100:2376`

| DOCKER_TLS_VERIFY
| 设置为 `1` 时启用安全的 HTTPS 协议（可选）

| DOCKER_CERT_PATH
| HTTPS 的证书和密钥文件的路径（如果 `DOCKER_TLS_VERIFY=1` 则为必需，否则忽略）
|===

还可以使用插件配置中的 `docker` 属性提供 Docker 守护进程连接信息。
下表总结了可用属性：

|===
| 属性 | 描述

| `context`
| 应从 Docker CLI https://docs.docker.com/engine/reference/commandline/cli/#configuration-files[配置文件] 中检索主机信息的 https://docs.docker.com/engine/context/working-with-contexts/[上下文] 名称

| `host`
| 包含 Docker 守护进程的主机和端口的 URL - 例如 `tcp://192.168.99.100:2376`

| `tlsVerify`
| 设置为 `true` 时启用安全的 HTTPS 协议（可选）

| `certPath`
| HTTPS 的证书和密钥文件的路径（如果 `tlsVerify` 为 `true` 则为必需，否则忽略）

| `bindHostToBuilder`
| 当为 `true` 时，`host` 属性的值将提供给为 CNB 构建器创建的容器（可选）
|===

有关更多详细信息，请参阅 xref:packaging-oci-image.adoc#build-image.examples.docker[示例]。

[[build-image.docker-registry]]
== Docker 仓库
如果 `builder` 或 `runImage` 属性指定的 Docker 镜像存储在需要身份验证的私有 Docker 镜像仓库中，则可以使用 `docker.builderRegistry` 属性提供身份验证凭据。

如果生成的 Docker 镜像要发布到 Docker 镜像仓库，则可以使用 `docker.publishRegistry` 属性提供身份验证凭据。

属性支持用户身份验证或身份令牌身份验证。
请查阅用于存储镜像的 Docker 仓库的文档，以获取有关支持的身份验证方法的更多信息。

下表总结了 `docker.builderRegistry` 和 `docker.publishRegistry` 的可用属性：

|===
| 属性 | 描述

| `username`
| Docker 镜像仓库用户的用户名。用户身份验证必需。

| `password`
| Docker 镜像仓库用户的密码。用户身份验证必需。

| `url`
| Docker 镜像仓库的地址。用户身份验证可选。

| `email`
| Docker 镜像仓库用户的电子邮件地址。用户身份验证可选。

| `token`
| Docker 镜像仓库用户的身份令牌。令牌身份验证必需。
|===

有关更多详细信息，请参阅 xref:packaging-oci-image.adoc#build-image.examples.docker[示例]。

[[build-image.customization]]
== 镜像自定义
插件调用 {url-buildpacks-docs}/concepts/components/builder/[构建器] 来协调镜像的生成。
构建器包含多个 {url-buildpacks-docs}/concepts/components/buildpack[构建包]，这些构建包可以检查应用程序以影响生成的镜像。
默认情况下，插件选择构建器镜像。
生成的镜像名称从项目属性中推断。

任务属性可用于配置构建器应如何操作项目。
下表总结了可用属性及其默认值：

|===
| 属性 | 命令行选项 | 描述 | 默认值

| `builder`
| `--builder`
| 要使用的构建器镜像的名称。
| `paketobuildpacks/builder-jammy-java-tiny:latest`

| `trustBuilder`
| `--trustBuilder`
| 是否将构建器视为 https://buildpacks.io/docs/for-platform-operators/how-to/integrate-ci/pack/concepts/trusted_builders/#what-is-a-trusted-builder[受信任的]。
| 如果构建器是 `paketobuildpacks/builder-jammy-java-tiny`、`paketobuildpacks/builder-noble-java-tiny`、`paketobuildpacks/builder-jammy-tiny`、`paketobuildpacks/builder-jammy-base`、`paketobuildpacks/builder-jammy-full`、`paketobuildpacks/builder-jammy-buildpackless-tiny`、`paketobuildpacks/builder-jammy-buildpackless-base`、`paketobuildpacks/builder-jammy-buildpackless-full`、`gcr.io/buildpacks/builder`、`heroku/builder` 之一，则为 `true`；否则为 `false`。

| `imagePlatform`
| `--imagePlatform`
a|任何构建器、运行和构建包镜像拉取的平台（操作系统和架构）。
必须为 `OS[/architecture[/variant]]` 形式，例如 `linux/amd64`、`linux/arm64` 或 `linux/arm/v5`。
请参阅所使用的构建器的文档以确定可用的镜像操作系统和架构选项。
| 无默认值，表示应使用主机机器的平台。

| `runImage`
| `--runImage`
| 要使用的运行镜像的名称。
| 无默认值，表示应使用构建器元数据中指定的运行镜像。

| `imageName`
| `--imageName`
| javadoc:org.springframework.boot.buildpack.platform.docker.type.ImageReference#of-java.lang.String-[生成的镜像的名称]。
| `docker.io/library/${project.name}:${project.version}`

| `pullPolicy`
| `--pullPolicy`
| javadoc:org.springframework.boot.buildpack.platform.build.PullPolicy[策略]，用于确定何时从仓库拉取构建器和运行镜像。
可接受的值为 `ALWAYS`、`NEVER` 和 `IF_NOT_PRESENT`。
| `ALWAYS`

| `environment`
|
| 应传递给构建器的环境变量。
| 空。

| `buildpacks`
|
a|构建器在构建镜像时应使用的构建包。
仅使用指定的构建包，覆盖构建器中包含的默认构建包。
构建包引用必须为以下形式之一：

* 构建器中的构建包 - `[urn:cnb:builder:]<buildpack ID>[@<version>]`
* 文件系统上目录中的构建包 - `[file://]<path>`
* 文件系统上 gzip 压缩的 tar (.tgz) 文件中的构建包 - `[file://]<path>/<file name>`
* OCI 镜像中的构建包 - `[docker://]<host>/<repo>[:<tag>][@<digest>]`
| 无，表示构建器应使用其中包含的构建包。

| `bindings`
|
a|https://docs.docker.com/storage/bind-mounts/[卷绑定挂载]，在构建镜像时应挂载到构建器容器。
绑定将在创建构建器容器时未经解析和验证传递给 Docker。
绑定必须为以下形式之一：

* `<host source path>:<container destination path>[:<options>]`
* `<host volume name>:<container destination path>[:<options>]`

其中 `<options>` 可以包含：

* `ro` 以在容器中以只读方式挂载卷
* `rw` 以在容器中以可读写方式挂载卷
* `volume-opt=key=value` 以指定由选项名称及其值组成的键值对
|

| `network`
| `--network`
| 构建器容器将配置使用的 https://docs.docker.com/network/#network-drivers[网络驱动程序]。
提供的值将在创建构建器容器时未经验证传递给 Docker。
|

| `cleanCache`
| `--cleanCache`
| 是否在构建前清理缓存。
| `false`

| `verboseLogging`
|
| 启用构建器操作的详细日志记录。
| `false`

| `publish`
| `--publishImage`
| 是否将生成的镜像发布到 Docker 仓库。
| `false`

| `tags`
|
| 应用于生成镜像的一个或多个附加标签的列表。
提供给 `tags` 选项的值应为 *完整* 的镜像引用。
有关更多详细信息，请参阅 xref:packaging-oci-image.adoc#build-image.customization.tags[标签部分]。
|

| `buildWorkspace`
|
| 构建器和构建包在镜像构建期间用于存储文件的临时工作区。
值可以是命名卷或绑定挂载位置。
| Docker 守护进程中的命名卷，名称从镜像名称派生。

| `buildCache`
|
| 包含由构建包创建的层并由镜像构建过程使用的缓存。
值可以是命名卷或绑定挂载位置。
| Docker 守护进程中的命名卷，名称从镜像名称派生。

| `launchCache`
|
| 包含由构建包创建的层并由镜像启动过程使用的缓存。
值可以是命名卷或绑定挂载位置。
| Docker 守护进程中的命名卷，名称从镜像名称派生。

| `createdDate`
| `--createdDate`
| 用于设置生成镜像元数据中 `Created` 字段的日期。
值必须为 ISO 8601 即时格式的字符串，或 `now` 以使用当前日期和时间。
| 启用 https://buildpacks.io/docs/features/reproducibility/[构建可重现性] 的固定日期。

| `applicationDirectory`
| `--applicationDirectory`
| 应用程序内容将上传到构建器镜像中的目录路径。
应用程序内容在生成的镜像中也位于此位置。
| `/workspace`

| `securityOptions`
| `--securityOptions`
| https://docs.docker.com/engine/reference/run/#security-configuration[安全选项]，将应用于构建器容器，作为字符串值数组提供
| 在 Linux 和 macOS 上为 `["label=disable"]`，在 Windows 上为 `[]`

|===

NOTE: 插件使用 JavaPlugin 的 `targetCompatibility` 属性检测项目的目标 Java 兼容性。
当使用默认的 Paketo 构建器和构建包时，插件会指示构建包安装相同的 Java 版本。
你可以覆盖此行为，如 xref:packaging-oci-image.adoc#build-image.examples.builder-configuration[构建器配置] 示例所示。

NOTE: 默认构建器 `paketobuildpacks/builder-jammy-java-tiny:latest` 不包含 shell。
如果应用程序需要 shell 来运行启动脚本（例如，当应用 {url-gradle-docs-application-plugin}[`application` 插件] 以生成分发 zip 存档时），应覆盖 `builder` 配置以使用包含 shell 的构建器，例如 `paketobuildpacks/builder-jammy-base:latest` 或 `paketobuildpacks/builder-jammy-full:latest`。

[[build-image.customization.tags]]
=== 标签格式
提供给 `tags` 选项的值应为 *完整* 的镜像引用。
接受的格式为 `[domainHost:port/][path/]name[:tag][@digest]`。

如果缺少域，则默认为 `docker.io`。
如果缺少路径，则默认为 `library`。
如果缺少标签，则默认为 `latest`。

一些示例：

* `my-image` 导致镜像引用 `docker.io/library/my-image:latest`
* `my-repository/my-image` 导致 `docker.io/my-repository/my-image:latest`
* `example.com/my-repository/my-image:1.0.0` 将按原样使用

[[build-image.examples]]
== 示例

[[build-image.examples.custom-image-builder]]
=== 自定义镜像构建器和运行镜像
如果需要自定义用于创建镜像的构建器或用于启动构建镜像的运行镜像，请按以下示例配置任务：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-builder.gradle[tags=builder]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-builder.gradle.kts[tags=builder]
----
======

此配置将使用名为 `mine/java-cnb-builder` 且标签为 `latest` 的构建器镜像，以及名为 `mine/java-cnb-run` 且标签为 `latest` 的运行镜像。

构建器和运行镜像也可以在命令行中指定，如下例所示：

[source,shell]
----
$ gradle bootBuildImage --builder=mine/java-cnb-builder --runImage=mine/java-cnb-run
----

[[build-image.examples.builder-configuration]]
=== 构建器配置
如果构建器公开了配置选项，则可以使用 `environment` 属性设置这些选项。

以下示例展示了 {url-paketo-docs-java-buildpack}/#configuring-the-jvm-version[配置 JVM 版本]，供 Paketo Java 构建包在构建时使用：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env.gradle[tags=env]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env.gradle.kts[tags=env]
----
======

如果在 Docker 守护进程和构建包下载工件的网络位置之间存在网络代理，则需要配置构建器以使用代理。
当使用 Paketo 构建器时，可以通过设置 `HTTPS_PROXY` 和/或 `HTTP_PROXY` 环境变量来完成此操作，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env-proxy.gradle[tags=env]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env-proxy.gradle.kts[tags=env]
----
======

[[build-image.examples.runtime-jvm-configuration]]
=== 运行时 JVM 配置
Paketo Java 构建包通过设置 `JAVA_TOOL_OPTIONS` 环境变量 {url-paketo-docs-java-buildpack}/#runtime-jvm-configuration[配置 JVM 运行时环境]。
可以修改构建包提供的 `JAVA_TOOL_OPTIONS` 值，以自定义在容器中启动应用程序镜像时的 JVM 运行时行为。

应存储在镜像中并应用于每次部署的环境变量修改可以按照 {url-paketo-docs}/buildpacks/configuration/#environment-variables[Paketo 文档] 中的描述进行设置，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env-runtime.gradle[tags=env-runtime]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env-runtime.gradle.kts[tags=env-runtime]
----
======

[[build-image.examples.custom-image-name]]
=== 自定义镜像名称
默认情况下，镜像名称从项目的 `name` 和 `version` 推断，类似于 `docker.io/library/${project.name}:${project.version}`。
你可以通过设置任务属性来控制名称，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-name.gradle[tags=image-name]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-name.gradle.kts[tags=image-name]
----
======

请注意，此配置未提供显式标签，因此使用 `latest`。
也可以指定标签，使用 `${project.version}`、构建中可用的任何属性或硬编码版本。

镜像名称也可以在命令行中指定，如下例所示：

[source,shell]
----
$ gradle bootBuildImage --imageName=example.com/library/my-app:v1
----

[[build-image.examples.buildpacks]]
=== 构建包
默认情况下，构建器将使用构建器镜像中包含的构建包，并按预定义的顺序应用它们。
可以提供一组替代的构建包，以应用未包含在构建器中的构建包，或更改包含的构建包的顺序。
当提供一个或多个构建包时，仅应用指定的构建包。

以下示例指示构建器使用打包在 `.tgz` 文件中的自定义构建包，然后使用构建器中包含的构建包。

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-buildpacks.gradle[tags=buildpacks]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-buildpacks.gradle.kts[tags=buildpacks]
----
======

构建包可以以下列任何形式指定。

位于 CNB 构建器中的构建包（如果只有一个构建包与 `buildpack-id` 匹配，则可以省略版本）：

* `urn:cnb:builder:buildpack-id`
* `urn:cnb:builder:buildpack-id@0.0.1`
* `buildpack-id`
* `buildpack-id@0.0.1`

包含构建包内容的目录路径（Windows 上不支持）：

* `\file:///path/to/buildpack/`
* `/path/to/buildpack/`

包含构建包内容的 gzip 压缩的 tar 文件路径：

* `\file:///path/to/buildpack.tgz`
* `/path/to/buildpack.tgz`

包含 https://buildpacks.io/docs/buildpack-author-guide/package-a-buildpack/[打包构建包] 的 OCI 镜像：

* `docker://example/buildpack`
* `docker:///example/buildpack:latest`
* `docker:///example/buildpack@sha256:45b23dee08...`
* `example/buildpack`
* `example/buildpack:latest`
* `example/buildpack@sha256:45b23dee08...`

[[build-image.examples.publish]]
=== 镜像发布
可以通过启用 `publish` 选项将生成的镜像发布到 Docker 仓库。

如果 Docker 仓库需要身份验证，则可以使用 `docker.publishRegistry` 属性配置凭据。
如果 Docker 仓库不需要身份验证，则可以省略 `docker.publishRegistry` 配置。

NOTE: 镜像将发布到的仓库由镜像名称的仓库部分确定（在这些示例中为 `docker.example.com`）。
如果配置了 `docker.publishRegistry` 凭据并包含 `url` 属性，则此值将传递给仓库，但不用于确定发布仓库的位置。

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-publish.gradle[tags=publish]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-publish.gradle.kts[tags=publish]
----
======

发布选项也可以在命令行中指定，如下例所示：

[source,shell]
----
$ gradle bootBuildImage --imageName=docker.example.com/library/my-app:v1 --publishImage
----

[[build-image.examples.caches]]
=== 构建器缓存和工作区配置
CNB 构建器缓存用于构建和启动镜像的层。
默认情况下，这些缓存作为命名卷存储在 Docker 守护进程中，名称从目标镜像的完整名称派生。
如果镜像名称频繁更改（例如，当项目版本用作镜像名称中的标签时），则缓存可能会频繁失效。

可以配置缓存卷以使用替代名称，从而更好地控制缓存生命周期，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-caches.gradle[tags=caches]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-caches.gradle.kts[tags=caches]
----
======

构建器和构建包在镜像构建期间需要存储临时文件的位置。
默认情况下，此临时构建工作区存储在命名卷中。

缓存和构建工作区可以配置为使用绑定挂载而不是命名卷，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-bind-caches.gradle[tags=caches]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-bind-caches.gradle.kts[tags=caches]
----
======

[[build-image.examples.docker]]
=== Docker 配置

[[build-image.examples.docker.minikube]]
==== minikube 的 Docker 配置
插件可以与 https://minikube.sigs.k8s.io/docs/tasks/docker_daemon/[minikube 提供的 Docker 守护进程] 通信，而不是默认的本地连接。

在 Linux 和 macOS 上，可以在启动 minikube 后使用命令 `eval $(minikube docker-env)` 设置环境变量。

插件也可以通过提供连接详细信息来配置为使用 minikube 守护进程，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host.gradle[tags=docker-host]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host.gradle.kts[tags=docker-host]
----
======

[[build-image.examples.docker.podman]]
==== podman 的 Docker 配置
插件可以与 https://podman.io/[podman 容器引擎] 通信。

可以通过提供连接详细信息将插件配置为使用 podman 本地连接，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host-podman.gradle[tags=docker-host]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host-podman.gradle.kts[tags=docker-host]
----
======

TIP: 安装 `podman` CLI 后，可以使用命令 `podman info --format='{{.Host.RemoteSocket.Path}}'` 获取此示例中 `docker.host` 配置属性的值。

[[build-image.examples.docker.colima]]
==== Colima 的 Docker 配置
插件可以与 https://github.com/abiosoft/colima[Colima] 提供的 Docker 守护进程通信。
可以使用以下命令设置 `DOCKER_HOST` 环境变量：

[source,shell,subs="verbatim,attributes"]
----
$ export DOCKER_HOST=$(docker context inspect colima -f '{{.Endpoints.docker.Host}}')
----

插件也可以通过提供连接详细信息来配置为使用 Colima 守护进程，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host-colima.gradle[tags=docker-host]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host-colima.gradle.kts[tags=docker-host]
----
======

[[build-image.examples.docker.auth]]
==== 身份验证的 Docker 配置
如果构建器或运行镜像存储在支持用户身份验证的私有 Docker 仓库中，则可以使用 `docker.builderRegistry` 属性提供身份验证详细信息，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-auth-user.gradle[tags=docker-auth-user]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-auth-user.gradle.kts[tags=docker-auth-user]
----
======

如果构建器或运行镜像存储在支持令牌身份验证的私有 Docker 仓库中，则可以使用 `docker.builderRegistry` 提供令牌值，如下例所示：

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-auth-token.gradle[tags=docker-auth-token]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-auth-token.gradle.kts[tags=docker-auth-token]
----
======

'''
[[build-image]]
== Packaging OCI Images
The plugin can create an https://github.com/opencontainers/image-spec[OCI image] from a jar or war file using https://buildpacks.io[Cloud Native Buildpacks] (CNB).
Images can be built using the `bootBuildImage` task.

NOTE: For security reasons, images build and run as non-root users.
See the {url-buildpacks-docs}/reference/spec/platform-api/#users[CNB specification] for more details.

The task is automatically created when the `java` or `war` plugin is applied and is an instance of {apiref-gradle-plugin-boot-build-image}[`BootBuildImage`].

[[build-image.docker-daemon]]
== Docker Daemon
The `bootBuildImage` task requires access to a Docker daemon.
The task will inspect local Docker CLI https://docs.docker.com/engine/reference/commandline/cli/#configuration-files[configuration files] to determine the current https://docs.docker.com/engine/context/working-with-contexts/[context] and use the context connection information to communicate with a Docker daemon.
If the current context can not be determined or the context does not have connection information, then the task will use a default local connection.
This works with https://docs.docker.com/install/[Docker Engine] on all supported platforms without configuration.

Environment variables can be set to configure the `bootBuildImage` task to use an alternative local or remote connection.
The following table shows the environment variables and their values:

|===
| Environment variable | Description

| DOCKER_CONFIG
| Location of Docker CLI https://docs.docker.com/engine/reference/commandline/cli/#configuration-files[configuration files] used to determine the current context (defaults to `$HOME/.docker`)

| DOCKER_CONTEXT
| Name of a https://docs.docker.com/engine/context/working-with-contexts/[context] that should be used to retrieve host information from Docker CLI configuration files (overrides `DOCKER_HOST`)

| DOCKER_HOST
| URL containing the host and port for the Docker daemon - for example `tcp://192.168.99.100:2376`

| DOCKER_TLS_VERIFY
| Enable secure HTTPS protocol when set to `1` (optional)

| DOCKER_CERT_PATH
| Path to certificate and key files for HTTPS (required if `DOCKER_TLS_VERIFY=1`, ignored otherwise)
|===

Docker daemon connection information can also be provided using `docker` properties in the plugin configuration.
The following table summarizes the available properties:

|===
| Property | Description

| `context`
| Name of a https://docs.docker.com/engine/context/working-with-contexts/[context] that should be used to retrieve host information from Docker CLI https://docs.docker.com/engine/reference/commandline/cli/#configuration-files[configuration files]

| `host`
| URL containing the host and port for the Docker daemon - for example `tcp://192.168.99.100:2376`

| `tlsVerify`
| Enable secure HTTPS protocol when set to `true` (optional)

| `certPath`
| Path to certificate and key files for HTTPS (required if `tlsVerify` is `true`, ignored otherwise)

| `bindHostToBuilder`
| When `true`, the value of the `host` property will be provided to the container that is created for the CNB builder (optional)
|===

For more details, see also xref:packaging-oci-image.adoc#build-image.examples.docker[examples].

[[build-image.docker-registry]]
== Docker Registry
If the Docker images specified by the `builder` or `runImage` properties are stored in a private Docker image registry that requires authentication, the authentication credentials can be provided using `docker.builderRegistry` properties.

If the generated Docker image is to be published to a Docker image registry, the authentication credentials can be provided using `docker.publishRegistry` properties.

Properties are provided for user authentication or identity token authentication.
Consult the documentation for the Docker registry being used to store images for further information on supported authentication methods.

The following table summarizes the available properties for `docker.builderRegistry` and `docker.publishRegistry`:

|===
| Property | Description

| `username`
| Username for the Docker image registry user. Required for user authentication.

| `password`
| Password for the Docker image registry user. Required for user authentication.

| `url`
| Address of the Docker image registry. Optional for user authentication.

| `email`
| E-mail address for the Docker image registry user. Optional for user authentication.

| `token`
| Identity token for the Docker image registry user. Required for token authentication.
|===

For more details, see also xref:packaging-oci-image.adoc#build-image.examples.docker[examples].

[[build-image.customization]]
== Image Customizations
The plugin invokes a {url-buildpacks-docs}/concepts/components/builder/[builder] to orchestrate the generation of an image.
The builder includes multiple {url-buildpacks-docs}/concepts/components/buildpack[buildpacks] that can inspect the application to influence the generated image.
By default, the plugin chooses a builder image.
The name of the generated image is deduced from project properties.

Task properties can be used to configure how the builder should operate on the project.
The following table summarizes the available properties and their default values:

|===
| Property | Command-line option | Description | Default value

| `builder`
| `--builder`
| Name of the builder image to use.
| `paketobuildpacks/builder-jammy-java-tiny:latest`

| `trustBuilder`
| `--trustBuilder`
| Whether to treat the builder as https://buildpacks.io/docs/for-platform-operators/how-to/integrate-ci/pack/concepts/trusted_builders/#what-is-a-trusted-builder[trusted].
| `true` if the builder is one of `paketobuildpacks/builder-jammy-java-tiny`, `paketobuildpacks/builder-noble-java-tiny`, `paketobuildpacks/builder-jammy-tiny`, `paketobuildpacks/builder-jammy-base`, `paketobuildpacks/builder-jammy-full`, `paketobuildpacks/builder-jammy-buildpackless-tiny`, `paketobuildpacks/builder-jammy-buildpackless-base`, `paketobuildpacks/builder-jammy-buildpackless-full`, `gcr.io/buildpacks/builder`, `heroku/builder`; `false` otherwise.

| `imagePlatform`
| `--imagePlatform`
a|The platform (operating system and architecture) of any builder, run, and buildpack images that are pulled.
Must be in the form of `OS[/architecture[/variant]]`, such as `linux/amd64`, `linux/arm64`, or `linux/arm/v5`.
Refer to documentation of the builder being used to determine the image OS and architecture options available.
| No default value, indicating that the platform of the host machine should be used.

| `runImage`
| `--runImage`
| Name of the run image to use.
| No default value, indicating the run image specified in Builder metadata should be used.

| `imageName`
| `--imageName`
| javadoc:org.springframework.boot.buildpack.platform.docker.type.ImageReference#of-java.lang.String-[Image name] for the generated image.
| `docker.io/library/${project.name}:${project.version}`

| `pullPolicy`
| `--pullPolicy`
| javadoc:org.springframework.boot.buildpack.platform.build.PullPolicy[Policy] used to determine when to pull the builder and run images from the registry.
Acceptable values are `ALWAYS`, `NEVER`, and `IF_NOT_PRESENT`.
| `ALWAYS`

| `environment`
|
| Environment variables that should be passed to the builder.
| Empty.

| `buildpacks`
|
a|Buildpacks that the builder should use when building the image.
Only the specified buildpacks will be used, overriding the default buildpacks included in the builder.
Buildpack references must be in one of the following forms:

* Buildpack in the builder - `[urn:cnb:builder:]<buildpack ID>[@<version>]`
* Buildpack in a directory on the file system - `[file://]<path>`
* Buildpack in a gzipped tar (.tgz) file on the file system - `[file://]<path>/<file name>`
* Buildpack in an OCI image - `[docker://]<host>/<repo>[:<tag>][@<digest>]`
| None, indicating the builder should use the buildpacks included in it.

| `bindings`
|
a|https://docs.docker.com/storage/bind-mounts/[Volume bind mounts] that should be mounted to the builder container when building the image.
The bindings will be passed unparsed and unvalidated to Docker when creating the builder container.
Bindings must be in one of the following forms:

* `<host source path>:<container destination path>[:<options>]`
* `<host volume name>:<container destination path>[:<options>]`

Where `<options>` can contain:

* `ro` to mount the volume as read-only in the container
* `rw` to mount the volume as readable and writable in the container
* `volume-opt=key=value` to specify key-value pairs consisting of an option name and its value
|

| `network`
| `--network`
| The https://docs.docker.com/network/#network-drivers[network driver] the builder container will be configured to use.
The value supplied will be passed unvalidated to Docker when creating the builder container.
|

| `cleanCache`
| `--cleanCache`
| Whether to clean the cache before building.
| `false`

| `verboseLogging`
|
| Enables verbose logging of builder operations.
| `false`

| `publish`
| `--publishImage`
| Whether to publish the generated image to a Docker registry.
| `false`

| `tags`
|
| A list of one or more additional tags to apply to the generated image.
The values provided to the `tags` option should be *full* image references.
See xref:packaging-oci-image.adoc#build-image.customization.tags[the tags section] for more details.
|

| `buildWorkspace`
|
| A temporary workspace that will be used by the builder and buildpacks to store files during image building.
The value can be a named volume or a bind mount location.
| A named volume in the Docker daemon, with a name derived from the image name.

| `buildCache`
|
| A cache containing layers created by buildpacks and used by the image building process.
The value can be a named volume or a bind mount location.
| A named volume in the Docker daemon, with a name derived from the image name.

| `launchCache`
|
| A cache containing layers created by buildpacks and used by the image launching process.
The value can be a named volume or a bind mount location.
| A named volume in the Docker daemon, with a name derived from the image name.

| `createdDate`
| `--createdDate`
| A date that will be used to set the `Created` field in the generated image's metadata.
The value must be a string in the ISO 8601 instant format, or `now` to use the current date and time.
| A fixed date that enables https://buildpacks.io/docs/features/reproducibility/[build reproducibility].

| `applicationDirectory`
| `--applicationDirectory`
| The path to a directory that application contents will be uploaded to in the builder image.
Application contents will also be in this location in the generated image.
| `/workspace`

| `securityOptions`
| `--securityOptions`
| https://docs.docker.com/engine/reference/run/#security-configuration[Security options] that will be applied to the builder container, provided as an array of string values
| `["label=disable"]` on Linux and macOS, `[]` on Windows

|===

NOTE: The plugin detects the target Java compatibility of the project using the JavaPlugin's `targetCompatibility` property.
When using the default Paketo builder and buildpacks, the plugin instructs the buildpacks to install the same Java version.
You can override this behavior as shown in the xref:packaging-oci-image.adoc#build-image.examples.builder-configuration[builder configuration] examples.

NOTE: The default builder `paketobuildpacks/builder-jammy-java-tiny:latest` does not include a shell.
Applications that require a shell to run a start script, as might be the case when the {url-gradle-docs-application-plugin}[`application` plugin] has been applied to generate a distribution zip archive, should override the `builder` configuration to use one that includes a shell, such as `paketobuildpacks/builder-jammy-base:latest` or `paketobuildpacks/builder-jammy-full:latest`.

[[build-image.customization.tags]]
=== Tags Format
The values provided to the `tags` option should be *full* image references.
The accepted format is `[domainHost:port/][path/]name[:tag][@digest]`.

If the domain is missing, it defaults to `docker.io`.
If the path is missing, it defaults to `library`.
If the tag is missing, it defaults to `latest`.

Some examples:

* `my-image` leads to the image reference `docker.io/library/my-image:latest`
* `my-repository/my-image` leads to `docker.io/my-repository/my-image:latest`
* `example.com/my-repository/my-image:1.0.0` will be used as is

[[build-image.examples]]
== Examples

[[build-image.examples.custom-image-builder]]
=== Custom Image Builder and Run Image
If you need to customize the builder used to create the image or the run image used to launch the built image, configure the task as shown in the following example:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-builder.gradle[tags=builder]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-builder.gradle.kts[tags=builder]
----
======

This configuration will use a builder image with the name `mine/java-cnb-builder` and the tag `latest`, and the run image named `mine/java-cnb-run` and the tag `latest`.

The builder and run image can be specified on the command line as well, as shown in this example:

[source,shell]
----
$ gradle bootBuildImage --builder=mine/java-cnb-builder --runImage=mine/java-cnb-run
----

[[build-image.examples.builder-configuration]]
=== Builder Configuration
If the builder exposes configuration options, those can be set using the `environment` property.

The following is an example of {url-paketo-docs-java-buildpack}/#configuring-the-jvm-version[configuring the JVM version] used by the Paketo Java buildpacks at build time:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env.gradle[tags=env]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env.gradle.kts[tags=env]
----
======

If there is a network proxy between the Docker daemon the builder runs in and network locations that buildpacks download artifacts from, you will need to configure the builder to use the proxy.
When using the Paketo builder, this can be accomplished by setting the `HTTPS_PROXY` and/or `HTTP_PROXY` environment variables as show in the following example:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env-proxy.gradle[tags=env]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env-proxy.gradle.kts[tags=env]
----
======

[[build-image.examples.runtime-jvm-configuration]]
=== Runtime JVM Configuration
Paketo Java buildpacks {url-paketo-docs-java-buildpack}/#runtime-jvm-configuration[configure the JVM runtime environment] by setting the `JAVA_TOOL_OPTIONS` environment variable.
The buildpack-provided `JAVA_TOOL_OPTIONS` value can be modified to customize JVM runtime behavior when the application image is launched in a container.

Environment variable modifications that should be stored in the image and applied to every deployment can be set as described in the {url-paketo-docs}/buildpacks/configuration/#environment-variables[Paketo documentation] and shown in the following example:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env-runtime.gradle[tags=env-runtime]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-env-runtime.gradle.kts[tags=env-runtime]
----
======

[[build-image.examples.custom-image-name]]
=== Custom Image Name
By default, the image name is inferred from the `name` and the `version` of the project, something like `docker.io/library/${project.name}:${project.version}`.
You can take control over the name by setting task properties, as shown in the following example:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-name.gradle[tags=image-name]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-name.gradle.kts[tags=image-name]
----
======

Note that this configuration does not provide an explicit tag so `latest` is used.
It is possible to specify a tag as well, either using `${project.version}`, any property available in the build or a hardcoded version.

The image name can be specified on the command line as well, as shown in this example:

[source,shell]
----
$ gradle bootBuildImage --imageName=example.com/library/my-app:v1
----

[[build-image.examples.buildpacks]]
=== Buildpacks
By default, the builder will use buildpacks included in the builder image and apply them in a pre-defined order.
An alternative set of buildpacks can be provided to apply buildpacks that are not included in the builder, or to change the order of included buildpacks.
When one or more buildpacks are provided, only the specified buildpacks will be applied.

The following example instructs the builder to use a custom buildpack packaged in a `.tgz` file, followed by a buildpack included in the builder.

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-buildpacks.gradle[tags=buildpacks]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-buildpacks.gradle.kts[tags=buildpacks]
----
======

Buildpacks can be specified in any of the forms shown below.

A buildpack located in a CNB Builder (version may be omitted if there is only one buildpack in the builder matching the `buildpack-id`):

* `urn:cnb:builder:buildpack-id`
* `urn:cnb:builder:buildpack-id@0.0.1`
* `buildpack-id`
* `buildpack-id@0.0.1`

A path to a directory containing buildpack content (not supported on Windows):

* `\file:///path/to/buildpack/`
* `/path/to/buildpack/`

A path to a gzipped tar file containing buildpack content:

* `\file:///path/to/buildpack.tgz`
* `/path/to/buildpack.tgz`

An OCI image containing a https://buildpacks.io/docs/buildpack-author-guide/package-a-buildpack/[packaged buildpack]:

* `docker://example/buildpack`
* `docker:///example/buildpack:latest`
* `docker:///example/buildpack@sha256:45b23dee08...`
* `example/buildpack`
* `example/buildpack:latest`
* `example/buildpack@sha256:45b23dee08...`

[[build-image.examples.publish]]
=== Image Publishing
The generated image can be published to a Docker registry by enabling a `publish` option.

If the Docker registry requires authentication, the credentials can be configured using `docker.publishRegistry` properties.
If the Docker registry does not require authentication, the `docker.publishRegistry` configuration can be omitted.

NOTE: The registry that the image will be published to is determined by the registry part of the image name (`docker.example.com` in these examples).
If `docker.publishRegistry` credentials are configured and include a `url` property, this value is passed to the registry but is not used to determine the publishing registry location.

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-publish.gradle[tags=publish]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-publish.gradle.kts[tags=publish]
----
======

The publish option can be specified on the command line as well, as shown in this example:

[source,shell]
----
$ gradle bootBuildImage --imageName=docker.example.com/library/my-app:v1 --publishImage
----

[[build-image.examples.caches]]
=== Builder Cache and Workspace Configuration
The CNB builder caches layers that are used when building and launching an image.
By default, these caches are stored as named volumes in the Docker daemon with names that are derived from the full name of the target image.
If the image name changes frequently, for example when the project version is used as a tag in the image name, then the caches can be invalidated frequently.

The cache volumes can be configured to use alternative names to give more control over cache lifecycle as shown in the following example:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-caches.gradle[tags=caches]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-caches.gradle.kts[tags=caches]
----
======

Builders and buildpacks need a location to store temporary files during image building.
By default, this temporary build workspace is stored in a named volume.

The caches and the build workspace can be configured to use bind mounts instead of named volumes, as shown in the following example:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-bind-caches.gradle[tags=caches]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-bind-caches.gradle.kts[tags=caches]
----
======

[[build-image.examples.docker]]
=== Docker Configuration

[[build-image.examples.docker.minikube]]
==== Docker Configuration for minikube
The plugin can communicate with the https://minikube.sigs.k8s.io/docs/tasks/docker_daemon/[Docker daemon provided by minikube] instead of the default local connection.

On Linux and macOS, environment variables can be set using the command `eval $(minikube docker-env)` after minikube has been started.

The plugin can also be configured to use the minikube daemon by providing connection details similar to those shown in the following example:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host.gradle[tags=docker-host]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host.gradle.kts[tags=docker-host]
----
======

[[build-image.examples.docker.podman]]
==== Docker Configuration for podman
The plugin can communicate with a https://podman.io/[podman container engine].

The plugin can be configured to use podman local connection by providing connection details similar to those shown in the following example:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host-podman.gradle[tags=docker-host]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host-podman.gradle.kts[tags=docker-host]
----
======

TIP: With the `podman` CLI installed, the command `podman info --format='{{.Host.RemoteSocket.Path}}'` can be used to get the value for the `docker.host` configuration property shown in this example.

[[build-image.examples.docker.colima]]
==== Docker Configuration for Colima
The plugin can communicate with the Docker daemon provided by https://github.com/abiosoft/colima[Colima].
The `DOCKER_HOST` environment variable can be set by using the following command:

[source,shell,subs="verbatim,attributes"]
----
$ export DOCKER_HOST=$(docker context inspect colima -f '{{.Endpoints.docker.Host}}')
----

The plugin can also be configured to use Colima daemon by providing connection details similar to those shown in the following example:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host-colima.gradle[tags=docker-host]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-host-colima.gradle.kts[tags=docker-host]
----
======

[[build-image.examples.docker.auth]]
==== Docker Configuration for Authentication
If the builder or run image are stored in a private Docker registry that supports user authentication, authentication details can be provided using `docker.builderRegistry` properties as shown in the following example:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-auth-user.gradle[tags=docker-auth-user]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-auth-user.gradle.kts[tags=docker-auth-user]
----
======

If the builder or run image is stored in a private Docker registry that supports token authentication, the token value can be provided using `docker.builderRegistry` as shown in the following example:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-auth-token.gradle[tags=docker-auth-token]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$packaging/boot-build-image-docker-auth-token.gradle.kts[tags=docker-auth-token]
----
======