[[publishing-your-application]]
= Publishing your Application



[[publishing-your-application.maven-publish]]
== Publishing with the Maven-publish Plugin

To publish your Spring Boot jar or war, add it to the publication using the `artifact` method on `MavenPublication`.
Pass the task that produces that artifact that you wish to publish to the `artifact` method.
For example, to publish the artifact produced by the default `bootJar` task:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$publishing/maven-publish.gradle[tags=publishing]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$publishing/maven-publish.gradle.kts[tags=publishing]
----
======



[[publishing-your-application.distribution]]
== Distributing with the Application Plugin

When the {url-gradle-docs-application-plugin}[`application` plugin] is applied a distribution named `boot` is created.
This distribution contains the archive produced by the `bootJar` or `bootWar` task and scripts to launch it on Unix-like platforms and Windows.
Zip and tar distributions can be built by the `bootDistZip` and `bootDistTar` tasks respectively.
To use the `application` plugin, its `mainClassName` property must be configured with the name of your application's main class.
