= 与 Actuator 集成
:encoding: utf-8
:numbered:

[[build-info]]
== 与 Actuator 集成

如果存在 `META-INF/build-info.properties` 文件，Spring Boot Actuator 会显示与构建相关的信息。
`build-info` 目标会生成这样的文件，其中包含项目的坐标和构建时间。
它还允许你添加任意数量的附加属性，如下例所示：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$build-info/pom.xml[tags=build-info]
----

此配置将在预期位置生成一个 `build-info.properties` 文件，并包含三个附加键。

NOTE: `java.version` 应该是项目中可用的常规属性。
它将按预期进行插值。

include::partial$goals/build-info.adoc[leveloffset=+1]

'''
[[build-info]]
== Integrating with Actuator

Spring Boot Actuator displays build-related information if a `META-INF/build-info.properties` file is present.
The `build-info` goal generates such file with the coordinates of the project and the build time.
It also allows you to add an arbitrary number of additional properties, as shown in the following example:

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$build-info/pom.xml[tags=build-info]
----

This configuration will generate a `build-info.properties` at the expected location with three additional keys.

NOTE: `java.version` is expected to be a regular property available in the project.
It will be interpolated as you would expect.

include::partial$goals/build-info.adoc[leveloffset=+1]
