= 使用插件
:encoding: utf-8
:numbered:

[[using]]
== 使用插件

Maven 用户可以继承 `spring-boot-starter-parent` 项目以获得合理的默认配置。父项目提供以下功能：

* 默认使用 Java 17 作为编译器级别。
* UTF-8 源代码编码。
* 使用 `-parameters` 进行编译。
* 从 `spring-boot-dependencies` POM 继承的依赖管理部分，管理常见依赖的版本。这种依赖管理允许你在自己的 POM 中使用这些依赖时省略 `<version>` 标签。
* 使用 `repackage` 执行 ID 执行 xref:maven-plugin:packaging.adoc#packaging.repackage-goal[`repackage` 目标]。
* 配置构建以能够生成 Native 镜像的 `native` 配置文件。
* 合理的 https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html[资源过滤]。
* 合理的插件配置（ https://github.com/ktoso/maven-git-commit-id-plugin[Git commit ID] 和 https://maven.apache.org/plugins/maven-shade-plugin/[shade]）。
* 对 `application.properties` 和 `application.yml` 的合理资源过滤，包括特定于配置文件的文件（例如 `application-dev.properties` 和 `application-dev.yml`）。

NOTE: 由于 `application.properties` 和 `application.yml` 文件接受 Spring 风格的占位符（`${...}`），Maven 过滤更改为使用 `@..@` 占位符。（你可以通过设置名为 `resource.delimiter` 的 Maven 属性来覆盖此行为。）

[NOTE]
====
`spring-boot-starter-parent` 设置了 `maven.compiler.release` 属性，该属性限制了 https://openjdk.org/jeps/247[如果它们修改系统模块] 的 `--add-exports`、`--add-reads` 和 `--patch-module` 选项。如果你需要使用这些选项，请取消设置 `maven.compiler.release`：

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<maven.compiler.release></maven.compiler.release>
----

然后配置源和目标选项：

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<maven.compiler.source>${java.version}</maven.compiler.source>
<maven.compiler.target>${java.version}</maven.compiler.target>
----
====

[[using.parent-pom]]
== 继承 Starter Parent POM

要配置项目以继承 `spring-boot-starter-parent`，请按如下方式设置 `parent`：

[source,xml,subs="verbatim,quotes,attributes"]
----
<!-- 从 Spring Boot 继承默认配置 -->
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>{version-spring-boot}</version>
</parent>
----

NOTE: 你只需要在此依赖项中指定 Spring Boot 版本号。如果你导入了其他启动器，可以安全地省略版本号。

通过此设置，你还可以通过覆盖项目中的属性来覆盖单个依赖项。例如，要使用不同版本的 SLF4J 库和 Spring Data 发布列车，你可以在 `pom.xml` 中添加以下内容：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$using/different-versions-pom.xml[tags=different-versions]
----

浏览 Spring Boot 参考文档中的 xref:appendix:dependency-versions/properties.adoc[依赖版本属性] 部分，以获取完整的依赖版本属性列表。

[[using.import]]
== 不使用 Parent POM 的 Spring Boot

你可能有一些原因不想继承 `spring-boot-starter-parent` POM。你可能需要使用自己的公司标准父 POM，或者你更喜欢显式声明所有 Maven 配置。

如果你不想使用 `spring-boot-starter-parent`，你仍然可以通过使用 `import` 范围的依赖项来保留依赖管理的优势（但不包括插件管理），如下所示：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$using/no-starter-parent-pom.xml[tags=no-starter-parent]
----

上述示例设置不允许你通过使用属性覆盖单个依赖项，如上所述。要实现相同的结果，你需要在项目的 `dependencyManagement` 部分中添加条目，**在** `spring-boot-dependencies` 条目之前。例如，要使用不同版本的 SLF4J 库和 Spring Data 发布列车，你可以在 `pom.xml` 中添加以下元素：

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$using/no-starter-parent-override-dependencies-pom.xml[tags=no-starter-parent-override-dependencies]
----

[[using.overriding-command-line]]
== 在命令行上覆盖设置

插件提供了许多以 `spring-boot` 开头的用户属性，允许你从命令行自定义配置。

例如，你可以在运行应用程序时调整启用的配置文件，如下所示：

[source,shell]
----
$ mvn spring-boot:run -Dspring-boot.run.profiles=dev,local
----

如果你希望在允许在命令行上覆盖的同时设置默认值，你应该结合使用用户提供的项目属性和 MOJO 配置。

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$using/default-and-override-pom.xml[tags=default-and-override]
----

上述配置确保默认启用 `local` 和 `dev`。现在已公开了一个专用属性，也可以在命令行上覆盖它：

[source,shell]
----
$ mvn spring-boot:run -Dapp.profiles=test
----

'''
[[using]]
== Using the Plugin

Maven users can inherit from the `spring-boot-starter-parent` project to obtain sensible defaults.
The parent project provides the following features:

* Java 17 as the default compiler level.
* UTF-8 source encoding.
* Compilation with `-parameters`.
* A dependency management section, inherited from the `spring-boot-dependencies` POM, that manages the versions of common dependencies.
This dependency management lets you omit `<version>` tags for those dependencies when used in your own POM.
* An execution of the xref:maven-plugin:packaging.adoc#packaging.repackage-goal[`repackage` goal] with a `repackage` execution id.
* A `native` profile that configures the build to be able to generate a Native image.
* Sensible https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html[resource filtering].
* Sensible plugin configuration (https://github.com/ktoso/maven-git-commit-id-plugin[Git commit ID], and https://maven.apache.org/plugins/maven-shade-plugin/[shade]).
* Sensible resource filtering for `application.properties` and `application.yml` including profile-specific files (for example, `application-dev.properties` and `application-dev.yml`)

NOTE: Since the `application.properties` and `application.yml` files accept Spring style placeholders (`${...}`), the Maven filtering is changed to use `@..@` placeholders.
(You can override that by setting a Maven property called `resource.delimiter`.)

[NOTE]
====
The `spring-boot-starter-parent` sets the `maven.compiler.release` property, which restricts the `--add-exports`, `--add-reads`, and `--patch-module` options https://openjdk.org/jeps/247[if they modify system modules].
In case you need to use those options, unset `maven.compiler.release`:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<maven.compiler.release></maven.compiler.release>
----

and then configure the source and the target options instead:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<maven.compiler.source>${java.version}</maven.compiler.source>
<maven.compiler.target>${java.version}</maven.compiler.target>
----
====



[[using.parent-pom]]
== Inheriting the Starter Parent POM

To configure your project to inherit from the `spring-boot-starter-parent`, set the `parent` as follows:

[source,xml,subs="verbatim,quotes,attributes"]
----
<!-- Inherit defaults from Spring Boot -->
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>{version-spring-boot}</version>
</parent>
----

NOTE: You should need to specify only the Spring Boot version number on this dependency.
If you import additional starters, you can safely omit the version number.

With that setup, you can also override individual dependencies by overriding a property in your own project.
For instance, to use a different version of the SLF4J library and the Spring Data release train, you would add the following to your `pom.xml`:

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$using/different-versions-pom.xml[tags=different-versions]
----

Browse the xref:appendix:dependency-versions/properties.adoc[Dependency Versions Properties] section in the Spring Boot reference for a complete list of dependency version properties.



[[using.import]]
== Using Spring Boot without the Parent POM

There may be reasons for you not to inherit from the `spring-boot-starter-parent` POM.
You may have your own corporate standard parent that you need to use or you may prefer to explicitly declare all your Maven configuration.

If you do not want to use the `spring-boot-starter-parent`, you can still keep the benefit of the dependency management (but not the plugin management) by using an `import` scoped dependency, as follows:

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$using/no-starter-parent-pom.xml[tags=no-starter-parent]
----

The preceding sample setup does not let you override individual dependencies by using properties, as explained above.
To achieve the same result, you need to add entries in the `dependencyManagement` section of your project **before** the `spring-boot-dependencies` entry.
For instance, to use a different version of the SLF4J library and the Spring Data release train, you could add the following elements to your `pom.xml`:

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$using/no-starter-parent-override-dependencies-pom.xml[tags=no-starter-parent-override-dependencies]
----



[[using.overriding-command-line]]
== Overriding Settings on the Command Line

The plugin offers a number of user properties, starting with `spring-boot`, to let you customize the configuration from the command line.

For instance, you could tune the profiles to enable when running the application as follows:

[source,shell]
----
$ mvn spring-boot:run -Dspring-boot.run.profiles=dev,local
----

If you want to both have a default while allowing it to be overridden on the command line, you should use a combination of a user-provided project property and MOJO configuration.

[source,xml,indent=0,subs="verbatim,attributes"]
----
include::example$using/default-and-override-pom.xml[tags=default-and-override]
----

The above makes sure that `local` and `dev` are enabled by default.
Now a dedicated property has been exposed, this can be overridden on the command line as well:

[source,shell]
----
$ mvn spring-boot:run -Dapp.profiles=test
----
